### ISSUE TITLE
Should we add a new device selector for SR-IOV PF's?

### ISSUE THREAD

**Issue by ahalim-intel** [intel/sriov-network-device-plugin#109]
I think it would be nice to have a PF based selectors(PF interface names or PCI addresses). Lets discuss this idea.

**Comment by pkdas** [comment]
Hi this is an excellent topic. I would like to join this dis

**Comment by zshi-redhat** [comment]
I think a PF based selectors will be helpful for:
1) backward compat with ``rootDevices`` configuration, I think kubevirt team is using this type of configuration in their project.
2) distinguish devices which have identical vendor ID, device ID and driver type (for example, two identical devices on the same host that are connected with different networks can be advertised as different network resources)

Some questions are:
1) From user perspective how they get to know which PF device name or PCI address is on the node when specifying it in the conf file?
2) Given a network device name or device PCI address, it can be any type of network devices with various drivers (not just PF device), do we want to support those devices as well? I think we actually already doing that with current driver selector that can be used to specify any type of driver such as virtio driver inside VM, this would make SR-IOV device plugin more generic for network devices and can be used in more advanced scenarios.

**Comment by ahalim-intel** [comment]
> I think a PF based selectors will be helpful for:
> 
> 1. backward compat with `rootDevices` configuration, I think kubevirt team is using this type of configuration in their project.

One main concern I have is this does not fit-well with cluster-wide resource config(using configMap). Because, an interface name 'enp2s0f1' OR a PCI address '0000:02:00.0' could mean completely different device on different node.
For example, a resource config like this: 
```
{
	"resourceName": "intel_sriov_enp2s0f1",
	"selectors": {
		"pf": ["enp2s0f1"]
	}
}
```
What we expect to happen when a host does not have a PF interface matching this name OR PCI addr?


> 2. distinguish devices which have identical vendor ID, device ID and driver type (for example, two identical devices on the same host that are connected with different networks can be advertised as different network resources)
> 
> Some questions are:
> 
> 1. From user perspective how they get to know which PF device name or PCI address is on the node when specifying it in the conf file?

This is probably the same scenario that have with currently supported PF PCI address based resource pool. The admin is expected to know which specific devices we are targeted.

 
> 2. Given a network device name or device PCI address, it can be any type of network devices with various drivers (not just PF device), do we want to support those devices as well? I think we actually already doing that with current driver selector that can be used to specify any type of driver such as virtio driver inside VM, this would make SR-IOV device plugin more generic for network devices and can be used in more advanced scenarios.

We are talking about SR-IOV network devices and add VFs from only those PF listed in the PF selector. Thus, the interface name and pci address are meant to me for SR-IOV PFs. If we want extend this for all sort of network devices then the selector list will very big and same as like manually figure out all the interface name/pci address and list them into the resource config. For those use-cases using other selectors would make more sense IMO.

**Comment by zshi-redhat** [comment]
> > I think a PF based selectors will be helpful for:
> > 
> > 1. backward compat with `rootDevices` configuration, I think kubevirt team is using this type of configuration in their project.
> 
> One main concern I have is this does not fit-well with cluster-wide resource config(using configMap). Because, an interface name 'enp2s0f1' OR a PCI address '0000:02:00.0' could mean completely different device on different node.
> For example, a resource config like this:
> 
> ```
> {
> 	"resourceName": "intel_sriov_enp2s0f1",
> 	"selectors": {
> 		"pf": ["enp2s0f1"]
> 	}
> }
> ```
> What we expect to happen when a host does not have a PF interface matching this name OR PCI addr?

Above should be considered as a limitation of PF based selectors when it's used in a heterogeneous environment, and I don't think we can solve the problem with PF selector itself without introducing other selectors like node selector or even network selector etc. we probably also need to understand better about the use case why PF selector is needed concerning above limitation, or is it possible to use other selectors instead? 

> 
> > 1. distinguish devices which have identical vendor ID, device ID and driver type (for example, two identical devices on the same host that are connected with different networks can be advertised as different network resources)
> > 
> > Some questions are:
> > 
> > 1. From user perspective how they get to know which PF device name or PCI address is on the node when specifying it in the conf file?
> 
> This is probably the same scenario that have with currently supported PF PCI address based resource pool. The admin is expected to know which specific devices we are targeted.

Right, the old ``rootDevices`` configuration has the same problem; 
This is just a minor regression compared with current selector based configuration which doesn't require the understanding of device name in term of vendor/device IDs, driver type etc.

> 
> > 1. Given a network device name or device PCI address, it can be any type of network devices with various drivers (not just PF device), do we want to support those devices as well? I think we actually already doing that with current driver selector that can be used to specify any type of driver such as virtio driver inside VM, this would make SR-IOV device plugin more generic for network devices and can be used in more advanced scenarios.
> 
> We are talking about SR-IOV network devices and add VFs from only those PF listed in the PF selector. Thus, the interface name and pci address are meant to me for SR-IOV PFs. If we want extend this for all sort of network devices then the selector list will very big and same as like manually figure out all the interface name/pci address and list them into the resource config. For those use-cases using other selectors would make more sense IMO.

Makes sense.
