### ISSUE TITLE
Handle VF creation and binding to appropriate device driver on init

### ISSUE THREAD

**Issue by krsna1729** [intel/sriov-network-device-plugin#116]
The device plugin could create VFs and bind the appropriate device device driver, and perform any driver specific initialization. This will reduce an extra step for administrators.

These won't be necessary -
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/9-multi-network/systemd/sriov.service
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/9-multi-network/systemd/sriov.sh

**Comment by mythi** [comment]
+1

**Comment by saberlilydian** [comment]
+1

**Comment by Levovar** [comment]
+1
could also do the PR sometime if project owners give positive feedback

**Comment by ahalim-intel** [comment]
We left out the VF creation and driver binding tasks out of the scope of this plugin.  The configuration for these tasks will be again very much node specific where we have moved SR-IOV device plugin discovery method more generic. We need node specific policy to handle those tasks and the [SR-IOV Network Operator](https://github.com/openshift/sriov-network-operator) does this pretty well. 

Having said that, I'd still be in favor of having some ansible scripts in this repo to handle these tasks if required and someone knows how to do them well.

**Comment by krsna1729** [comment]
No ansible, Just an optional flag for driver initialization. So how should we think about the repos under Openshift vs. Intel. They seem to have exact same ones. Is there a "blessed" way of using multus, sriov{cni/deviceplugin} with any other things, like the operator you mentioned etc.,?

**Comment by ahalim-intel** [comment]
The SR-IOV network operator is there to do everything else that sriov device plugin is not doing - i.e. pre-configure a node(kernel params, loading vfio-pci module, driver updates, NIC configurations), installing multus, sriov-cni, creating net CRDs etc.. All of those steps are important to have SR-IOV networking working in cluster and we cannot implement those all in device plugin.

Even though, these projects are in Intel and openshift repo and the name "SRIOV" is common, their functionality aren't.

**Comment by zshi-redhat** [comment]
> No ansible, Just an optional flag for driver initialization. So how should we think about the repos under Openshift vs. Intel. They seem to have exact same names. Is there a "blessed" way of using multus, sriov{cni/deviceplugin} with any other things, like the operator you mentioned etc.,?

For Multus, SR-IOV CNI, SR-IOV Network Device Plugin and Network Resources Injector, Intel repos are upstream, OpenShift are downstream. All the development work happens first in Intel upstream repo and will be considered to backport to OpenShift downstream repos based on its own release cadence. Feature wise, there might be difference depends on which release versions are used, but ultimately all the features will be the same.

SR-IOV Operator was created under OpenShift github org but it's an upstream project and anyone can consume and contribute under [LICENCE](https://github.com/openshift/sriov-network-operator/blob/master/LICENSE). We have seen folks using SR-IOV Operator in Kubernetes environment and reported success.  One example is kubevirt which I heard was using it in CI environment for automation of SR-IOV Provisioning etc.

**Comment by Levovar** [comment]
We actually went the Ansible way in Akraino REC, so you might consider checking it out if you would like to expand the repo with the automation of the initial setup.
Note though, that REC has a full POD (not the Kubernetes) description and config management layer, so the code would need some north-bound adaptation if you would like to re-use it in another project.

**Comment by killianmuldoon** [comment]
Closed as stale
