### ISSUE TITLE
AWS ENA usage

### ISSUE THREAD

**Issue by krsna1729** [intel/sriov-network-device-plugin#12]
Any ideas on how to use this plugin with AWS [Elastic Network Adapters](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI)? We will have a pool of NICs that are not SR-IOV capable (proabably they are VFs themselves). Can they still be managed by this device plugin?

**Comment by ahalim-intel** [comment]
Hi @krsna1729,
Current implementation of the sriov device plugin can discover VFs if their corresponding PF's from the host are readable through sysfs.
