### ISSUE TITLE
Not able to attach SRIOV VF in centos 7.5 with intel xxv710 Adapter.

### ISSUE THREAD

**Issue by jigar253** [intel/sriov-network-device-plugin#13]
Hi,

I would like to run sriov plugin on my Kubernetes Single Node cluster with Intel XXV710 Ethernet adapter with Multus and Flannel plugin, but i am facing below issue. can someone help me here.

Steps :

1) OS : Centos 7.5 "CentOS Linux release 7.5.1804 (Core)"
2) i make sure her that Link is up for ethernet interface p4p1, p4p2 in machine and having 8 Vfs each created and i40e driver version is 2.4.10
3) Below is my cat /proc/cmdline , where intel_iommu=on for SRIOV

#cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-862.9.1.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet intel_iommu=on

4) Install Docker on Centos machine and udpate to latest with "yum update"

 $ yum update
 $ yum install -y docker
 $ systemctl enable docker && systemctl start docker

5) Install kubeadm, kubelet, kubectl and disable Selinux
 
 $ cat <<EOF > /etc/yum.repos.d/kubernetes.repo
   [kubernetes]
   name=Kubernetes
   baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
   enabled=1
   gpgcheck=1
   repo_gpgcheck=1
   gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
   exclude=kube*
   EOF
 $ setenforce 0
 $ yum install -y kubelet kubeadm kubectl
 $ systemctl enable kubelet && systemctl start kubelet

kubelet, kubeadm and kubectl version is : 1.11.1
 
Make sure that selinux is disable here.

6) Ensure that net.bridge.bridge-nf-call-iptables is set to 1 in sysctl config

  $ cat <<EOF >  /etc/sysctl.d/k8s.conf
   net.bridge.bridge-nf-call-ip6tables = 1
   net.bridge.bridge-nf-call-iptables = 1
   EOF
  $ sysctl --system

7) make sure here that Kubelet is working fine in system 

   For that, i have  changed /etc/sysconfig/kubelet and add systemd for cgroup driver.
   KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

8) Reload daemon and restart Kubelet and export admin config file and start "kubadm init"

  $ systemctl daemon-reload
  $ systemctl restart kubelet
  $ export KUBECONFIG=/etc/kubernetes/admin.conf
  $ kubeadm init --pod-network-cidr=10.244.0.0/16

9) Compile Multus CNI plugin with below command. (Multus v2.0):

  $ git clone --branch v2.0 https://github.com/intel/multus-cni.git --single-branch
  $ cd multus-cni
  $ ./build 
  $ cp bin/multus /opt/cni/bin

10) Compile SRIOV CNI plugin with below command

  $ git clone https://github.com/Intel-Corp/sriov-cni.git
  $ cd sriov-cni
  $ git fetch
  $ git checkout dev/sriov-network-device-plugin-alpha
  $ ./build
  $ cp bin/sriov /opt/cni/bin

11 Compile SRIOV Device Plugin and CNI-Shim

  $ git clone https://github.com/intel/sriov-network-device-plugin.git
  
  and try to do ./build.sh, but it needs protoc , so i installed protoc from 
  https://github.com/google/protobuf/releases version 3.6.0

  also once protoc installed, it needs protoc-gen-go, so i took it
  protoc-gen-go from below location
 
  go get -u github.com/golang/protobuf/protoc-gen-go

  Here my
  GO version is 1.10.3
  protoc version is : 3.6.0 
  protoc-gen-go version :   ( Not able to get protoc-gen-go-version)

  but it gives me issue while compiling protobuf API ( Issue 1) 

 
  $ ./build.sh
  Building protobuf API
  Building SRIOV Device plugin
    # github.com/intel/sriov-network-device-plugin/api

  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:56:36: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:103:35: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:154:27: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:188:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:197:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)

  which i am not able to solve, so i disabled the compilation of protobuf API in build.sh and ran ./build.sh and it works fine.
  
  Disabled line in build.sh 
 
  # echo "Building protobuf API"
  # protoc -I api/ -I${GOPATH}/src api/api.proto --go_out=plugins=grpc:api

12. copy cni shim binary from bin directory

  $ cp bin/cnishim /opt/cni/bin

13. Copy the CNI Shim Configuration file from the Deployments folder to the CNI Configuration diectory

  $ cp deployments/cni-conf.json /etc/cni/net.d/

14. Create MULTUS CRD for Network object using YAMML

  $ kubectl create -f ./deployments/crdnetworks.yaml

  $ cat .d/eployment/crdnetworks.yaml

   apiVersion: apiextensions.k8s.io/v1beta1
   kind: CustomResourceDefinition
   metadata:
   # name must match the spec fields below, and be in the form: <plural>.<group>
   name: networks.kubernetes.cni.cncf.io
   spec:
   # group name to use for REST API: /apis/<group>/<version>
   group: kubernetes.cni.cncf.io
   # version name to use for REST API: /apis/<group>/<version>
   version: v1
   # either Namespaced or Cluster
   scope: Namespaced
   names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: networks
    # singular name to be used as an alias on the CLI and for display
    singular: network
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Network
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - net

15. create flannel network using YAML

   $ kubectl create -f ./deployments/flannel-network.yaml

   $ cat flannel-network.yaml
   
    apiVersion: "kubernetes.cni.cncf.io/v1"
    kind: Network
    metadata:
      name: flannel-net 
    spec:
      config: '{
      "cniVersion": "0.3.0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }'

16. create SRIOV network using YAML
  
   $ kubectl create -f ./deployments/sriov-network.yaml
  
   $ cat sriov-network.yaml
   
   apiVersion: "kubernetes.cni.cncf.io/v1"
   kind: Network
   metadata:
     name: sriov-conf
   spec:
    config: '{
    "type": "sriov",
    "if0": "p4p1",
    "ipam": {
            "type": "host-local",
            "subnet": "10.56.217.0/24",
            "rangeStart": "10.56.217.171",
            "rangeEnd": "10.56.217.181",
            "routes": [
                    { "dst": "0.0.0.0/0" }
            ],
            "gateway": "10.56.217.1"
    }
   }'

17. show networks which we have created 

   $ kubectl get network

   NAME           AGE
   cnishim-net1   2d
   flannel-net    2d
   sriov-conf     3h

18. create cni shim network CRD

   $ kubectl create -f deployments/cnishim-crd.yaml

19. Run build docker script to create SRIOV Network Device Plugin Docker image

   $ cd deployments/
   $ ./build_docker.sh

20. Create SRIOV Network Device Plugin Pod 

   $ kubectl create -f pod-sriovdp.yaml

21. Execute the SRIOV Network Device Plugin binary from within the Pod

   $ kubectl exec -it sriov-device-plugin bash
   $ /usr/bin/sriovdp --logtostderr -v 10

I0801 10:43:04.420898  119325 sriov-device-plugin.go:456] Starting SRIOV Network Device Plugin...
I0801 10:43:04.422727  119325 sriov-device-plugin.go:98] Checking checkpoint file
I0801 10:43:04.422991  119325 sriov-device-plugin.go:111] Restored PodUID: 1e4a9119-954c-11e8-b990-246e9664ea64 DeviceIDs : {0000:82:02.2,}
I0801 10:43:04.423039  119325 sriov-device-plugin.go:111] Restored PodUID: 177c4e53-9559-11e8-b637-246e9664ea64 DeviceIDs : {0000:82:0a.5,}
I0801 10:43:04.423077  119325 sriov-device-plugin.go:111] Restored PodUID: 9ae69b30-9559-11e8-b637-246e9664ea64 DeviceIDs : {0000:82:02.4,}
I0801 10:43:04.423415  119325 sriov-device-plugin.go:232] Discovering SRIOV network device[s]
I0801 10:43:04.423786  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/cni0/device/sriov_numvfs
I0801 10:43:04.423825  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/docker0/device/sriov_numvfs
I0801 10:43:04.423848  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/em1/device/sriov_numvfs
I0801 10:43:04.423876  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/em2/device/sriov_numvfs
I0801 10:43:04.423901  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/em3/device/sriov_numvfs
I0801 10:43:04.423929  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/em4/device/sriov_numvfs
I0801 10:43:04.423955  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/flannel.1/device/sriov_numvfs
I0801 10:43:04.423977  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/lo/device/sriov_numvfs
I0801 10:43:04.423997  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1/device/sriov_numvfs
I0801 10:43:04.424032  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_0/device/sriov_numvfs
I0801 10:43:04.424059  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_1/device/sriov_numvfs
I0801 10:43:04.424084  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_2/device/sriov_numvfs
I0801 10:43:04.424109  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_3/device/sriov_numvfs
I0801 10:43:04.424135  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_4/device/sriov_numvfs
I0801 10:43:04.424160  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_5/device/sriov_numvfs
I0801 10:43:04.424185  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_6/device/sriov_numvfs
I0801 10:43:04.424209  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p1_7/device/sriov_numvfs
I0801 10:43:04.424237  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2/device/sriov_numvfs
I0801 10:43:04.424261  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_0/device/sriov_numvfs
I0801 10:43:04.424286  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_1/device/sriov_numvfs
I0801 10:43:04.424310  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_2/device/sriov_numvfs
I0801 10:43:04.424335  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_3/device/sriov_numvfs
I0801 10:43:04.424359  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_4/device/sriov_numvfs
I0801 10:43:04.424384  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_5/device/sriov_numvfs
I0801 10:43:04.424409  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_6/device/sriov_numvfs
I0801 10:43:04.424433  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/p4p2_7/device/sriov_numvfs
I0801 10:43:04.424458  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/veth6ccb8686/device/sriov_numvfs
I0801 10:43:04.424479  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/veth966bf1cd/device/sriov_numvfs
I0801 10:43:04.424498  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/vetha29e46c9/device/sriov_numvfs
I0801 10:43:04.424518  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/vethc64ab3e6/device/sriov_numvfs
I0801 10:43:04.424538  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/vethe2ae7a53/device/sriov_numvfs
I0801 10:43:04.424568  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/virbr0/device/sriov_numvfs
I0801 10:43:04.424588  119325 sriov-device-plugin.go:134] Checking for file /sys/class/net/virbr0-nic/device/sriov_numvfs
I0801 10:43:04.424609  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/em1/device/sriov_totalvfs
I0801 10:43:04.424699  119325 sriov-device-plugin.go:175] Total number of VFs for device em1 is 7
I0801 10:43:04.424712  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: em1
I0801 10:43:04.424760  119325 sriov-device-plugin.go:190] Number of Configured VFs for device em1 is 0
I0801 10:43:04.424772  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/em2/device/sriov_totalvfs
I0801 10:43:04.424817  119325 sriov-device-plugin.go:175] Total number of VFs for device em2 is 7
I0801 10:43:04.424827  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: em2
I0801 10:43:04.424874  119325 sriov-device-plugin.go:190] Number of Configured VFs for device em2 is 0
I0801 10:43:04.424885  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/em3/device/sriov_totalvfs
I0801 10:43:04.424976  119325 sriov-device-plugin.go:175] Total number of VFs for device em3 is 7
I0801 10:43:04.424988  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: em3
I0801 10:43:04.425038  119325 sriov-device-plugin.go:190] Number of Configured VFs for device em3 is 0
I0801 10:43:04.425049  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/em4/device/sriov_totalvfs
I0801 10:43:04.425094  119325 sriov-device-plugin.go:175] Total number of VFs for device em4 is 7
I0801 10:43:04.425105  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: em4
I0801 10:43:04.425148  119325 sriov-device-plugin.go:190] Number of Configured VFs for device em4 is 0
I0801 10:43:04.425159  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/p4p1/device/sriov_totalvfs
I0801 10:43:04.425204  119325 sriov-device-plugin.go:175] Total number of VFs for device p4p1 is 64
I0801 10:43:04.425214  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: p4p1
I0801 10:43:04.425258  119325 sriov-device-plugin.go:190] Number of Configured VFs for device p4p1 is 8
I0801 10:43:04.425303  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 0 is 0000:82:02.0
I0801 10:43:04.425358  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 1 is 0000:82:02.1
I0801 10:43:04.425394  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 2 is 0000:82:02.2
I0801 10:43:04.425428  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 3 is 0000:82:02.3
I0801 10:43:04.425462  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 4 is 0000:82:02.4
I0801 10:43:04.425495  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 5 is 0000:82:02.5
I0801 10:43:04.425530  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 6 is 0000:82:02.6
I0801 10:43:04.425575  119325 sriov-device-plugin.go:213] PCI Address for device p4p1, VF 7 is 0000:82:02.7
I0801 10:43:04.425661  119325 sriov-device-plugin.go:163] Sriov Capable Path: /sys/class/net/p4p2/device/sriov_totalvfs
I0801 10:43:04.425740  119325 sriov-device-plugin.go:175] Total number of VFs for device p4p2 is 64
I0801 10:43:04.425775  119325 sriov-device-plugin.go:177] SRIOV capable device discovered: p4p2
I0801 10:43:04.425847  119325 sriov-device-plugin.go:190] Number of Configured VFs for device p4p2 is 8
I0801 10:43:04.425904  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 0 is 0000:82:0a.0
I0801 10:43:04.425973  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 1 is 0000:82:0a.1
I0801 10:43:04.426028  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 2 is 0000:82:0a.2
I0801 10:43:04.426081  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 3 is 0000:82:0a.3
I0801 10:43:04.426134  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 4 is 0000:82:0a.4
I0801 10:43:04.426186  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 5 is 0000:82:0a.5
I0801 10:43:04.426242  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 6 is 0000:82:0a.6
I0801 10:43:04.426301  119325 sriov-device-plugin.go:213] PCI Address for device p4p2, VF 7 is 0000:82:0a.7
I0801 10:43:04.426332  119325 sriov-device-plugin.go:237] Starting SRIOV Network Device Plugin server at: /var/lib/kubelet/device-plugins/sriovNet.sock
I0801 10:43:04.427032  119325 sriov-device-plugin.go:262] SRIOV Network Device Plugin server started serving
I0801 10:43:04.428492  119325 sriov-device-plugin.go:482] SRIOV Network Device Plugin registered with the Kubelet
I0801 10:43:04.428759  119325 sriov-device-plugin.go:333] ListAndWatch: send devices &ListAndWatchResponse{Devices:[&Device{ID:0000:82:02.0,Health:Healthy,} &Device{ID:0000:82:02.1,Health:Healthy,} &Device{ID:0000:82:02.3,Health:Healthy,} &Device{ID:0000:82:02.4,Health:Healthy,} &Device{ID:0000:82:0a.3,Health:Healthy,} &Device{ID:0000:82:02.5,Health:Healthy,} &Device{ID:0000:82:0a.4,Health:Healthy,} &Device{ID:0000:82:0a.7,Health:Healthy,} &Device{ID:0000:82:02.2,Health:Healthy,} &Device{ID:0000:82:02.7,Health:Healthy,} &Device{ID:0000:82:0a.0,Health:Healthy,} &Device{ID:0000:82:0a.5,Health:Healthy,} &Device{ID:0000:82:02.6,Health:Healthy,} &Device{ID:0000:82:0a.1,Health:Healthy,} &Device{ID:0000:82:0a.2,Health:Healthy,} &Device{ID:0000:82:0a.6,Health:Healthy,}],}

I0801 10:54:47.212294  119325 sriov-device-plugin.go:363] PodUID:  & Container Name:  in Allocate
I0801 10:54:47.212371  119325 sriov-device-plugin.go:365] DeviceID in Allocate: 0000:82:0a.4
I0801 10:54:47.212386  119325 sriov-device-plugin.go:382] PCI Addrs allocated: 0000:82:0a.4,

22. Deploy Test pod
 
  $ kubectl create -f pod-tc1.yaml

  $ cat pod-tc1.yaml file 

   apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  labels:
    env: test
  annotations:
      kubernetes.v1.cni.cncf.io/networks: cnishim-net1
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov: '1'
      limits:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov: '1'

23. check interface list in testpod1, which is not showing SRIOV interface ( issue 2)

    [root@localhost deployments]#  kubectl exec -it testpod1 -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 0a:58:0a:f4:00:14 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.20/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::24dd:d6ff:fe60:3ba7/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever

SO in summary, I am facing below two issues

Issue 1: 

  Not able to compile Protobuf API with 

  GO version 1.10.3 
  protoc version is : 3.6.0 
  protoc-gen-go version :   ( Not able to get protoc-gen-go version)

  $ ./build.sh
  Building protobuf API
  Building SRIOV Device plugin
    # github.com/intel/sriov-network-device-plugin/api

  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:56:36: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:103:35: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:154:27: undefined: proto.InternalMessageInfo
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:188:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
  gopath/src/github.com/intel/sriov-network-device-plugin/api/api.pb.go:197:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)

Issue 2:

  Evenif I keep same protocbuf API got from git ( Not compiling)  and try to attach SRIOV VF , it is not attaching with Kubernetes pod.

  [root@localhost deployments]#  kubectl exec -it testpod1 -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 0a:58:0a:f4:00:14 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.20/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::24dd:d6ff:fe60:3ba7/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever

**Comment by ahalim-intel** [comment]
Hi @jigar253 ,
It looks like Multus is not configured as a default CNI plugin for your setup and not being invoked thus bypassing the network annotation altogether. As you're using kubeadm for your setup there are some [examples and documentation](https://github.com/intel/multus-cni/tree/v2.0/examples) on how to setup Multus.

To fix protoc issue you can trythe followings:

## Install protoc
$ curl -sOL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip && \
    unzip protoc-3.2.0-linux-x86_64.zip -d protoc3 && \
    mv protoc3/bin/* /usr/local/bin/ && mv protoc3/include/* /usr/local/include/

## Install protobuf 1.0
$ go get -u github.com/golang/protobuf/proto && \
  go get -u github.com/golang/protobuf/protoc-gen-go && \
  cd /go/src/github.com/golang/protobuf && git checkout -q v1.0.0 && \
  make install

**Comment by jigar253** [comment]
Thanks @ahalim-intel , I am able to solve my both issue#1 and issue#2
