### ISSUE TITLE
Using latest sriov dp image (May 29, 2019) will cause fail to resource registration.

### ISSUE THREAD

**Issue by mJace** [intel/sriov-network-device-plugin#130]
Just realized that there is a new update of sriov device plugin image at may 29.
And this version of image will fail when doing sriov vf resource registration.  
Can not register the VF for given PF root address in `/etc/pcidp/config.json`  

After I switch back the image tag for v2.1.0, everything work fine as it was.

**Comment by zshi-redhat** [comment]
@mJace thanks for reporting the issue!
On May 29, we merged all new features from feature/device_selectors branch to master branch which changed the way how sriovdp is configured.
would you please help to check if your `/etc/pcidp/config.json` applies to the [new configuration format](https://github.com/intel/sriov-network-device-plugin#config-parameters)? Basically there is no `rootDevice` config support anymore, instead please use PF name filter to expose VF resources from the same PF.

**Comment by mJace** [comment]
@zshi-redhat  Thanks for the fast reply!
Sorry that I didn't catch up with the new configuration format.
You may close this issue.

Btw the way, the `drivers` in selector just works like some filter right?
will it related to some driver re-binding like what we do in dpdk?

**Comment by zshi-redhat** [comment]
> @zshi-redhat Thanks for the fast reply!
> Sorry that I didn't catch up with the new configuration format.
> You may close this issue.
> 
sure, once you confirm the new config format works, we can close it.

> Btw the way, the `drivers` in selector just works like some filter right?
> will it related to some driver re-binding like what we do in dpdk?

yes, the `drivers` filter will only select devices of the given driver type. All the selectors are optional, if you'd like to use VF from a PF, then PF selector would be just enough. The order of selectors applied by device plugin would be vendor id, device id, drivers, pf name.

**Comment by zshi-redhat** [comment]
Closing per above comments, feel free to re-open if the issue still exist.
