### ISSUE TITLE
Removing prefix from k8s.v1.cni.cncf.io/resourceName annotation

### ISSUE THREAD

**Issue by pperiyasamy** [intel/sriov-network-device-plugin#145]
While creating net-attach-def object, it's needed to provide prefix name with `intel.com` for the k8s.v1.cni.cncf.io/resourceName annotation.
Can it be removed ?

sample net-attach-def:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-network",
  "vlan": 2222,
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
```

**Comment by ahalim-intel** [comment]
Kubernetes device plugin api uses the entire "vendor-domain/resource" name as the key for resource endpoint. This is also the resource name identifier for allocated resources in container. So, the answer is no and we need the full resource name as used by the device plugin api to get device information.

**Comment by pperiyasamy** [comment]
@ahalim-intel ah! yes. I see it. Looks it can be customized with  -resource-prefix command line parameter. Can you make it configurable (by default intel.com) in [sriovdp-daemonset.yaml](https://github.com/intel/sriov-network-device-plugin/blob/master/images/sriovdp-daemonset.yaml)

**Comment by zshi-redhat** [comment]
> @ahalim-intel ah! yes. I see it. Looks it can be customized with -resource-prefix command line parameter. Can you make it configurable (by default intel.com) in [sriovdp-daemonset.yaml](https://github.com/intel/sriov-network-device-plugin/blob/master/images/sriovdp-daemonset.yaml)

This is now configurable in `sriovdp-daemonset.yaml` via `--resource-prefix`.
