### ISSUE TITLE
VM worker with VFs (igb_uio) unable to allocate device to pod

### ISSUE THREAD

**Issue by ErMaVi** [intel/sriov-network-device-plugin#151]
**What Happened:**
The sriov-network-device-plugin ignores VFs attached to a VM if these VFs are attached to a DPDK driver.

**What you expect to happen:**
VFs running DPDK drivers show up in the k8s node allocatable devices

**Anything else we need to know:**
Kubernetes version (use kubectl version):
v1.15.1

**OS**
Linux k8s-master 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**confgMap for sriov-network-device-plugin**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "drivers": ["igbvf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "drivers": ["igb_uio"]
                }
            }
        ]
    }
```

**logs from kube-sriov-device-plugin**
```
I0726 16:38:55.091365   16198 manager.go:70] Using Kubelet Plugin Registry Mode
I0726 16:38:55.091818   16198 main.go:44] resource manager reading configs
I0726 16:38:55.092687   16198 manager.go:98] ResourceList: [{ResourceName:intel_sriov_netdevice IsRdma:false Selectors:{Vendors:[8086] Devices:[] Drivers:[igbvf] PfNames:[] LinkTypes:[]}} {ResourceName:intel_sriov_dpdk IsRdma:false Selectors:{Vendors:[] Devices:[] Drivers:[igb_uio] PfNames:[] LinkTypes:[]}}]
I0726 16:38:55.093015   16198 main.go:60] Discovering host network devices
I0726 16:38:55.093057   16198 manager.go:179] discovering host network devices
I0726 16:38:55.149207   16198 manager.go:209] discoverDevices(): device found: 0000:00:03.0     02              Red Hat, Inc.           Virtio network device
E0726 16:38:55.149346   16198 manager.go:230] discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:00:03.0/net: no such file or directory"
I0726 16:38:55.149683   16198 manager.go:209] discoverDevices(): device found: 0000:00:07.0     02              Red Hat, Inc.           Virtio network device
E0726 16:38:55.149769   16198 manager.go:230] discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:00:07.0/net: no such file or directory"
I0726 16:38:55.149781   16198 manager.go:209] discoverDevices(): device found: 0000:00:08.0     02              Red Hat, Inc.           Virtio network device
E0726 16:38:55.149877   16198 manager.go:230] discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:00:08.0/net: no such file or directory"
I0726 16:38:55.149889   16198 manager.go:209] discoverDevices(): device found: 0000:00:09.0     02              Intel Corporation       I350 Ethernet Controller Virtual Func...
I0726 16:38:55.150219   16198 manager.go:278] ens9 added to linkWatchList
I0726 16:38:55.150386   16198 manager.go:209] discoverDevices(): device found: 0000:00:0a.0     02              Intel Corporation       I350 Ethernet Controller Virtual Func...
I0726 16:38:55.150584   16198 manager.go:278] ens10 added to linkWatchList
I0726 16:38:55.150785   16198 manager.go:209] discoverDevices(): device found: 0000:00:0b.0     02              Intel Corporation       I350 Ethernet Controller Virtual Func...
E0726 16:38:55.150882   16198 manager.go:230] discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:00:0b.0/net: no such file or directory"
I0726 16:38:55.150899   16198 manager.go:209] discoverDevices(): device found: 0000:00:0c.0     02              Intel Corporation       I350 Ethernet Controller Virtual Func...
E0726 16:38:55.151000   16198 manager.go:230] discoverDevices() error adding new device: "open /sys/bus/pci/devices/0000:00:0c.0/net: no such file or directory"
I0726 16:38:55.151013   16198 main.go:66] Initializing resource servers
I0726 16:38:55.151020   16198 manager.go:108] number of config: 2
I0726 16:38:55.151027   16198 manager.go:111]
I0726 16:38:55.151033   16198 manager.go:112] Creating new ResourcePool: intel_sriov_netdevice
I0726 16:38:55.151046   16198 factory.go:144] device added: [pciAddr: 0000:00:09.0, vendor: 8086, device: 1520, driver: igbvf]
I0726 16:38:55.151054   16198 factory.go:144] device added: [pciAddr: 0000:00:0a.0, vendor: 8086, device: 1520, driver: igbvf]
I0726 16:38:55.151070   16198 manager.go:125] New resource server is created for intel_sriov_netdevice ResourcePool
I0726 16:38:55.151078   16198 manager.go:111]
I0726 16:38:55.151084   16198 manager.go:112] Creating new ResourcePool: intel_sriov_dpdk
I0726 16:38:55.151096   16198 manager.go:125] New resource server is created for intel_sriov_dpdk ResourcePool
I0726 16:38:55.151106   16198 main.go:72] Starting all servers...
```

**Comment by ErMaVi** [comment]
This patches the issue for me, I see the VFs getting assigned to the pod if I ignore the "net" directory, which doesn't exist for igb_uio devices in VMs, not sure about BM interfaces. The pod gets its requested VFs  even after restarts with this kludge.
```
+++ b/pkg/utils/utils.go
@@ -66,7 +66,7 @@ func GetPfName(pciAddr string) (string, error) {
                        path := filepath.Join(sysBusPci, pciAddr, "net")
                        files, err = ioutil.ReadDir(path)
                        if err != nil {
-                               return "", err
+                               return "", nil
                        }
                        if len(files) < 1 {
                                return "", fmt.Errorf("no interface name found for device %s", pciAddr)
```

**Comment by ahalim-intel** [comment]
@ErMaVi Current implementation of this plugin mainly focused on Baremetal deployment. We haven't really considered yet deploying device plugin with Multus and SR-IOV CNI plugin in VM environment. There are number of challenges:

1. We need to get access to PF interface for administrative tasks required to setup a VF
2. Determining device health status

Which VM should have access to the PF control plane? All of them? It looks like every VM will demand to have access to PF to setup a VF. I welcome any solution that could address those issues in safe and secure manner for VM scenarios.

**Comment by ErMaVi** [comment]
Thanks for your response.

I'm interested in a DPDK application running in a k8s cluster in the public cloud. Cloud providers will generally provide VMs.  In this scenario there's no need for Multus or SR-IOV CNI plugin, there's no need to add an IP address to the VF since it will be taken over by the application. (Although we could pass an IP/MAC/VLAN address as environment variables into the pod, and have the DPDK application use that, in that case we would use Multus and SR-IOV plugins). 
My understanding is that a cloud provider will pass a VF (or several) to a VM. The VM will have no access whatsoever to the PF underneath, there cannot be any administrative tasks performed on the PF since that would affect other VMs. Once the VF is bound to the igb_uio driver, and stops using the linux driver, the "net" directory will disappear since the VF will now belong to the user space application. **In this scenario, the network device plugin could simply attach the device to the pod requesting igb_uio devices.** 
I'm not sure about how to determine the health of such a device though, the kernel will not have access to it and only a DPDK application should be able to access it. But perhaps this is not necessary since the DPDK application running in the pod should be able to determine the health of the device and take action.

The steps outlined above are roughly these:

1. On VM boot - the VFs get bound to the igb_uio DPDK driver
2. The sriov-network-device-plugin identifies the igb_uio devices in each k8s node
3. A pod requesting an igb_uio device will get the device attached, if such a device exists in one of the nodes in the cluster.
4. Pod's DPDK application will init the igb_uio device and use the IP passed in the pods environment.
5. DPDK application can monitor the igb_uio device and take action if unhealthy
6. When a POD ceases to exist, the sriov-network-device-plugin should return the igb_uio device to the free pool.

**Comment by pperiyasamy** [comment]
As a timely workaround, you can make use of sr-iov network device plugin v2.1.0, that works without selector configuration.

{
    "resourceList":
    [
        {
            "resourceName": "sriov_net_A",
            "rootDevices": ["0000:05:01.0", "0000:05:02.0", "0000:05:03.0"],
            "sriovMode": false,
            "deviceType": "uio"
        }
    ]
}

**Comment by killianmuldoon** [comment]
@ErMaVi can you update on whether or not this solution worked for you?

**Comment by killianmuldoon** [comment]
Closing as stale.
