### ISSUE TITLE
Is mlx4_en supported?

### ISSUE THREAD

**Issue by hymgg** [intel/sriov-network-device-plugin#159]
Hello,

We enabled sriov on 2 types of NIC,

1.) Broadcom Inc. and subsidiaries NetXtreme II BCM57810 10 Gigabit Ethernet Multi Function (rev 10)

2.) Mellanox Technologies MT27520 Family [ConnectX-3 Pro]

Somehow the device plugin recognized first one, not the 2nd, did we miss some config or the 2nd one is not supported?

$ cat configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_net_A",
                "selectors": {
                    "vendors": ["14e4"],
                    "devices": ["16af"],
                    "drivers": ["bnx2x"],
                    "pfNames": ["eno31"]
                }
            },
            {
                "resourceName": "sriov_net_B",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1004"],
                    "drivers": ["mlx4_en"],
                    "pfNames": ["ens6"]
                }
            }
        ]
    }

Input for sriov_net_B:

# grep PCI_SLOT_NAME /sys/class/net/*/device/uevent|grep af:0
/sys/class/net/enp175s1d1/device/uevent:PCI_SLOT_NAME=0000:af:01.0
/sys/class/net/enp175s1/device/uevent:PCI_SLOT_NAME=0000:af:01.0
/sys/class/net/ens6d1/device/uevent:PCI_SLOT_NAME=0000:af:00.0
/sys/class/net/ens6/device/uevent:PCI_SLOT_NAME=0000:af:00.0
/sys/class/net/ens6f1d1/device/uevent:PCI_SLOT_NAME=0000:af:00.1
/sys/class/net/ens6f1/device/uevent:PCI_SLOT_NAME=0000:af:00.1
/sys/class/net/ens6f2d1/device/uevent:PCI_SLOT_NAME=0000:af:00.2
/sys/class/net/ens6f2/device/uevent:PCI_SLOT_NAME=0000:af:00.2
/sys/class/net/ens6f3d1/device/uevent:PCI_SLOT_NAME=0000:af:00.3
/sys/class/net/ens6f3/device/uevent:PCI_SLOT_NAME=0000:af:00.3
/sys/class/net/ens6f4d1/device/uevent:PCI_SLOT_NAME=0000:af:00.4
/sys/class/net/ens6f4/device/uevent:PCI_SLOT_NAME=0000:af:00.4
/sys/class/net/ens6f5d1/device/uevent:PCI_SLOT_NAME=0000:af:00.5
/sys/class/net/ens6f5/device/uevent:PCI_SLOT_NAME=0000:af:00.5
/sys/class/net/ens6f6d1/device/uevent:PCI_SLOT_NAME=0000:af:00.6
/sys/class/net/ens6f6/device/uevent:PCI_SLOT_NAME=0000:af:00.6
/sys/class/net/ens6f7d1/device/uevent:PCI_SLOT_NAME=0000:af:00.7
/sys/class/net/ens6f7/device/uevent:PCI_SLOT_NAME=0000:af:00.7

# lspci -nvmms af:00.0
Slot:	af:00.0
Class:	0200
Vendor:	15b3
Device:	1007
SVendor:	19e5
SDevice:	df1e
PhySlot:	6
NUMANode:	1

# ethtool -i ens6
driver: mlx4_en
version: 4.0-0
firmware-version: 2.42.5000
expansion-rom-version: 
bus-info: 0000:af:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes

$ kubectl logs kube-sriov-device-plugin-amd64-2ctzb -n kube-system
I0805 22:45:05.563224   39872 manager.go:70] Using Kubelet Plugin Registry Mode
I0805 22:45:05.563370   39872 main.go:44] resource manager reading configs
I0805 22:45:05.563560   39872 manager.go:98] ResourceList: [{ResourceName:sriov_net_A IsRdma:false Selectors:{Vendors:[14e4] Devices:[16af] Drivers:[bnx2x] PfNames:[eno31]}} {ResourceName:sriov_net_B IsRdma:false Selectors:{Vendors:[15b3] Devices:[1004] Drivers:[mlx4_en] PfNames:[ens6]}}]
I0805 22:45:05.563611   39872 main.go:60] Discovering host network devices
I0805 22:45:05.563619   39872 manager.go:179] discovering host network devices
I0805 22:45:05.600919   39872 manager.go:209] discoverDevices(): device found: 0000:1b:00.0	02          	Intel Corporation   	Ethernet Connection X722 for 10GbE ba...
I0805 22:45:05.601278   39872 manager.go:278] eno1 added to linkWatchList
I0805 22:45:05.604969   39872 manager.go:209] discoverDevices(): device found: 0000:1b:00.1	02          	Intel Corporation   	Ethernet Connection X722 for 10GbE ba...
I0805 22:45:05.605275   39872 manager.go:278] eno2 added to linkWatchList
I0805 22:45:05.606467   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.0	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.606707   39872 manager.go:278] eno30 added to linkWatchList
I0805 22:45:05.606781   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.1	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.607019   39872 manager.go:278] eno50 added to linkWatchList
I0805 22:45:05.607093   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.2	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.607326   39872 manager.go:278] eno31 added to linkWatchList
I0805 22:45:05.607348   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.3	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.607582   39872 manager.go:278] eno51 added to linkWatchList
I0805 22:45:05.607658   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.4	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.607884   39872 manager.go:278] eno32 added to linkWatchList
I0805 22:45:05.607957   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.5	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.608175   39872 manager.go:278] eno52 added to linkWatchList
I0805 22:45:05.608248   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.6	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.608476   39872 manager.go:278] eno33 added to linkWatchList
I0805 22:45:05.608551   39872 manager.go:209] discoverDevices(): device found: 0000:3b:00.7	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.608779   39872 manager.go:278] eno53 added to linkWatchList
I0805 22:45:05.608855   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.0	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.609154   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.1	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.609404   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.2	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.609658   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.3	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.609927   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.4	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.610172   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.5	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.610415   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.6	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.610663   39872 manager.go:209] discoverDevices(): device found: 0000:3b:03.7	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.610912   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.0	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.611154   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.1	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.611416   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.2	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.611656   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.3	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.611906   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.4	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.612208   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.5	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.612450   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.6	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.612690   39872 manager.go:209] discoverDevices(): device found: 0000:3b:04.7	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.612953   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.0	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.613175   39872 manager.go:278] eno40 added to linkWatchList
I0805 22:45:05.613231   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.1	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.613456   39872 manager.go:278] eno60 added to linkWatchList
I0805 22:45:05.613516   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.2	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.613731   39872 manager.go:278] eno41 added to linkWatchList
I0805 22:45:05.613787   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.3	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.614007   39872 manager.go:278] eno61 added to linkWatchList
I0805 22:45:05.614067   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.4	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.614277   39872 manager.go:278] eno42 added to linkWatchList
I0805 22:45:05.614333   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.5	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.614562   39872 manager.go:278] eno62 added to linkWatchList
I0805 22:45:05.614619   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.6	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.614833   39872 manager.go:278] eno43 added to linkWatchList
I0805 22:45:05.614894   39872 manager.go:209] discoverDevices(): device found: 0000:3c:00.7	02          	Broadcom Inc. and...	NetXtreme II BCM57810 10 Gigabit Ethe...
I0805 22:45:05.615109   39872 manager.go:278] eno63 added to linkWatchList
I0805 22:45:05.615172   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.0	02          	Mellanox Technolo...	MT27520 Family [ConnectX-3 Pro]         
I0805 22:45:05.615582   39872 manager.go:278] ens6 added to linkWatchList
I0805 22:45:05.615607   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.1	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.616500   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.2	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.617449   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.3	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.618506   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.4	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.619697   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.5	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.620903   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.6	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.622185   39872 manager.go:209] discoverDevices(): device found: 0000:af:00.7	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.623546   39872 manager.go:209] discoverDevices(): device found: 0000:af:01.0	02          	Mellanox Technolo...	MT27500/MT27520 Family [ConnectX-3/Co...
I0805 22:45:05.624969   39872 main.go:66] Initializing resource servers
I0805 22:45:05.624976   39872 manager.go:108] number of config: 2
I0805 22:45:05.624981   39872 manager.go:111] 
I0805 22:45:05.624984   39872 manager.go:112] Creating new ResourcePool: sriov_net_A
I0805 22:45:05.625007   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.0, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625012   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.1, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625016   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.2, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625020   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.3, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625024   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.4, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625028   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.5, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625031   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.6, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625034   39872 factory.go:132] device added: [pciAddr: 0000:3b:03.7, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625039   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.0, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625044   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.1, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625047   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.2, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625050   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.3, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625053   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.4, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625059   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.5, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625064   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.6, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625067   39872 factory.go:132] device added: [pciAddr: 0000:3b:04.7, vendor: 14e4, device: 16af, driver: bnx2x]
I0805 22:45:05.625080   39872 manager.go:125] New resource server is created for sriov_net_A ResourcePool
I0805 22:45:05.625084   39872 manager.go:111] 
I0805 22:45:05.625087   39872 manager.go:112] Creating new ResourcePool: sriov_net_B
I0805 22:45:05.625096   39872 manager.go:125] New resource server is created for sriov_net_B ResourcePool
I0805 22:45:05.625101   39872 main.go:72] Starting all servers...
I0805 22:45:05.625142   39872 server.go:190] starting sriov_net_A device plugin endpoint at: sriov_net_A.sock
I0805 22:45:05.626101   39872 server.go:216] sriov_net_A device plugin endpoint started serving
I0805 22:45:05.626147   39872 server.go:190] starting sriov_net_B device plugin endpoint at: sriov_net_B.sock
I0805 22:45:05.626590   39872 server.go:216] sriov_net_B device plugin endpoint started serving
I0805 22:45:05.626615   39872 main.go:77] All servers started.
I0805 22:45:05.626627   39872 main.go:78] Listening for term signals
I0805 22:45:07.253575   39872 server.go:105] Plugin: sriov_net_B.sock gets registered successfully at Kubelet
I0805 22:45:07.253576   39872 server.go:105] Plugin: sriov_net_A.sock gets registered successfully at Kubelet
I0805 22:45:07.253602   39872 server.go:130] ListAndWatch(sriov_net_A) invoked
I0805 22:45:07.253610   39872 server.go:130] ListAndWatch(sriov_net_B) invoked
I0805 22:45:07.253617   39872 server.go:138] ListAndWatch(sriov_net_B): send devices &ListAndWatchResponse{Devices:[],}
I0805 22:45:07.253612   39872 server.go:138] ListAndWatch(sriov_net_A): send devices &ListAndWatchResponse{Devices:[&Device{ID:0000:3b:03.6,Health:Healthy,} &Device{ID:0000:3b:03.7,Health:Healthy,} &Device{ID:0000:3b:04.2,Health:Healthy,} &Device{ID:0000:3b:04.6,Health:Healthy,} &Device{ID:0000:3b:04.7,Health:Healthy,} &Device{ID:0000:3b:03.1,Health:Healthy,} &Device{ID:0000:3b:03.3,Health:Healthy,} &Device{ID:0000:3b:04.0,Health:Healthy,} &Device{ID:0000:3b:04.1,Health:Healthy,} &Device{ID:0000:3b:04.4,Health:Healthy,} &Device{ID:0000:3b:03.2,Health:Healthy,} &Device{ID:0000:3b:04.3,Health:Healthy,} &Device{ID:0000:3b:03.0,Health:Healthy,} &Device{ID:0000:3b:03.4,Health:Healthy,} &Device{ID:0000:3b:03.5,Health:Healthy,} &Device{ID:0000:3b:04.5,Health:Healthy,}],}

Thanks.   -Jessica

**Comment by moshe010** [comment]
The short answer is no see [1]. The reason that it is not working is because ConnectX-3 Pro architecture is different in a sense that PF as 2 netdevice unlink ConnectX-4 which is PF has 1 netdevice. This is the reason you see only the first netvice.


[1] - https://github.com/intel/sriov-network-device-plugin/blob/master/README.md#supported-sriov-nics

**Comment by hymgg** [comment]
@moshe010 Thank you. The broadcom nic wasn't on the list either, and it worked, thought ConnectX-3 Pro might have a chance too. Right, the PF has 2 devices.

**Comment by moshe010** [comment]
ConnectX-4  and above should work for you.
