### ISSUE TITLE
Support LAG/LACP with SRIOV VF/PF

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-network-device-plugin#169]
## What would you like to be added?
Currently the SRIOV networks don't have any link redundancy. If the PF fails or cable fails then the connectivity to the network is lost. The SRIOV DP and SRIOV need to support Link redundancy/LACP using multiple VFs from PFs across multiple NICs

## What is the use case for this feature / enhancement?
Production grade networks for Telcos need HA, Link redundancy. It can also provide higher aggregated BW, for instance 4 10G ports can be combined to provide 40G throughput

I have added support for LACP/LAG using VFs in SRIOV-DP and in SRIOV.
If this is considered as desired and valuable enhancement I can provide the code changes in SRIOVDP and SRIOV CNI

**Comment by pkdas** [comment]
This is the use case for bare-metal K8S running NFV datapath or control path applications

**Comment by Levovar** [comment]
isn't it the case that once you configured LAG/LACP you will be only able to use those specific VFs on top of which you have configured it?
which is a little bit counterproductive with VFs, considering you can have 60 of them :)

AFAIK active-standby bonds/teams are the only usable alternatives

**Comment by killianmuldoon** [comment]
@pkdas is this configuration covered by the [bond cni](https://github.com/intel/bond-cni)?

**Comment by killianmuldoon** [comment]
Closing as stale
