### ISSUE TITLE
What's the proper way to trigger scan the device again?

### ISSUE THREAD

**Issue by mJace** [intel/sriov-network-device-plugin#178]
What's the proper way to let sriov device plugin to scan the VF again?
For example, forget to create VF before running sriov dp daemonSet
or change VF device numbers after sriov dp daemonSet's enumeration is done.

For now, I just delete the pods of sriov dp. so that the daemonSet will create the new pod to enumerate again.
Wondering if there is a proper way to do this.

**Comment by zshi-redhat** [comment]
I did the same by deleting daemon pod or re-create the daemon.
Ideally this would be triggered by a controller which monitors the change of VF provisioning and re-load device plugin daemon if necessary. There is a [SR-IOV Operator](https://github.com/openshift/sriov-network-operator) example which makes use of Kubernetes Operator framework to implement such controller.

**Comment by killianmuldoon** [comment]
closing as stale
