### ISSUE TITLE
Impossible to scan VFs: "Link not found"

### ISSUE THREAD

**Issue by gautier8535** [intel/sriov-network-device-plugin#180]
We setup a k8s cluster with SRIOV, using the latest versions of dp (3.0.0) and cni (2.1.0).
SRIOV is enabled in the BIOS and in we added intel_iommu=on in the grub conf file.
All VFs are well listed with IP a command.
However DP pod is not able to register the VFs to K8s, we are getting the following error in the logs:

kubectl logs -n kube-system kube-sriov-device-plugin-amd64-lxr4l
I0925 02:20:29.093410      14 manager.go:209] discoverDevices(): device found: 0000:3b:10.5     02              Intel Corporation       Ethernet Virtual Function 700 Series
E0925 02:20:29.093550      14 manager.go:254] expected to get valid host interface with name p1p4_21: "Link not found"
I0925 02:20:29.093599      14 manager.go:259] excluding interface p1p4_21:  route entry found: [{Ifindex: 4 Dst: <nil> Src: <nil> Gw: 169.254.1.1 Flags: [] Table: 254} {Ifindex: 4 Dst: 169.254.1.1/32 Src: <nil> Gw: <nil> Flags: [] Table: 254}]

Any idea what could be wrong ?

### Component Versions
nfvpe/sriov-device-plugin:v3.0.0
nfvpe/sriov-cni:v2.1.0

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin: nfvpe/sriov-device-plugin:v3.0.0
|SR-IOV CNI Plugin: nfvpe/sriov-cni:v2.1.0
|Multus: docker.io/nfvpe/multus:v3.1.autoconf
|Kubernetes: 1.12.7
|OS: centos 7.6

##### Device pool config file location (Try '/etc/pcidp/config.json')
{
    "resourceList":
    [
                {
            "resourceName": "sriov_net_ingress",
            "rootDevices": [  "3b:00.0" ],
            "sriovMode": true,
            "deviceType": "netdevice"
        }
        ,                {
            "resourceName": "sriov_net_egress",
            "rootDevices": [  "3b:00.1" ],
            "sriovMode": true,
            "deviceType": "netdevice"
        }
                    ]
}

**Comment by zshi-redhat** [comment]
@gautier8535 Hi, it looks like you were using old config format (rootDevices, sriovMode etc) which are supported in v2.1.0 onwards (including v2.1.0). If you'd like to use v3.0.0, please change the device plugin config according to examples in master [README](https://github.com/intel/sriov-network-device-plugin#config-parameters) file.

From above log, `p1p4_21` is excluded from allocatable device list because it was configured with a route, do you have an IP configured on top of it, maybe try to remove the IP address and run device plugin again.

btw, can you see the `p1p4_21` interface via `ip link show p1p4_21`?

**Comment by TothFerenc** [comment]
Make sure you have `hostNetwork: true` in your Pod spec.

**Comment by gautier8535** [comment]
> 
> 
> @gautier8535 Hi, it looks like you were using old config format (rootDevices, sriovMode etc) which are supported in v2.1.0 onwards (including v2.1.0). If you'd like to use v3.0.0, please change the device plugin config according to examples in master [README](https://github.com/intel/sriov-network-device-plugin#config-parameters) file.
> 
> From above log, `p1p4_21` is excluded from allocatable device list because it was configured with a route, do you have an IP configured on top of it, maybe try to remove the IP address and run device plugin again.
> 
> btw, can you see the `p1p4_21` interface via `ip link show p1p4_21`?

Thank you so much for your reply! I will have a try

**Comment by killianmuldoon** [comment]
@gautier8535 did you find a resolution for this?

**Comment by killianmuldoon** [comment]
Closed as stale
