### ISSUE TITLE
VF devices added incorrectly into the resource pools

### ISSUE THREAD

**Issue by pperiyasamy** [intel/sriov-network-device-plugin#184]
### What happened?
There are two worker nodes which are having resource pool configuration in config.json like below.
**worker -1**
```
{
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "drivers": ["i40evf"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk_vfio_device",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "drivers": ["vfio-pci"],
                "pfNames": ["ens3f1"]
            }
        },
        {
            "resourceName": "intel_sriov_hostdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "pfNames": ["ens3f2"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk_uio_device",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "pfNames": ["ens3f3"]
            }
        }
    ]
}
```
**worker-2**
```
{
    "resourceList": [{
            "resourceName": "intel_sriov_dpdk_uio_device",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "pfNames": ["0000:b5:00.0","0000:b6:00.0","0000:c9:00.0","0000:ca:00.0"]
            }
        }
    ]
}
```
The VF devices ("0000:b5:00.0","0000:b6:00.0","0000:c9:00.0","0000:ca:00.0") in worker-2 are added into resource pools intel_sriov_hostdevice and intel_sriov_dpdk_uio_device.

### What did you expect to happen?

The VF devices should be added only into resource pool intel_sriov_dpdk_uio_device and not to intel_sriov_hostdevice.

### Anything else we need to know?
When intel_sriov_hostdevice resource pool contains the config with drivers included, then VFs on the worker-2 are added correctly only into intel_sriov_dpdk_uio_device resource pool. 
It looks device selectors [filter logic](https://github.com/intel/sriov-network-device-plugin/blob/master/pkg/resources/deviceSelectors.go#L82) has to be also enhanced as dev.GetPFName() is empty here.
```
        {
            "resourceName": "intel_sriov_hostdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c"],
                "drivers": ["i40evf"],
                "pfNames": ["ens3f2"]
            }
        },
```
### Component Versions

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |master|
|Kubernetes                   |1.16.2|

**Comment by zshi-redhat** [comment]
@pperiyasamy how did you apply device plugin config files to different worker nodes? I thought we onlhy support one single config file for the whole cluster.
And in the pfName selector of worker-2 config file, should it use PF name instead of PCI addresses?

**Comment by pperiyasamy** [comment]
@zshi-redhat  Thanks for looking into it.

> how did you apply device plugin config files to different worker nodes? I thought we onlhy support one single config file for the whole cluster.

The above configuration are content of /etc/pcidp/config.json file from each worker node. 
But the config map is created like below for the whole cluster.
```
# kubectl get configmap sriovdp-config -n kube-system -o yaml
apiVersion: v1
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["i40evf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk_vfio_device",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["ens3f1"]
                }
            },
            {
                "resourceName": "intel_sriov_hostdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "pfNames": ["ens3f2"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk_uio_device",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "pfNames": ["ens3f3","0000:b5:00.0","0000:b6:00.0","0000:c9:00.0","0000:ca:00.0"]
                }
            }
        ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-11-11T12:28:30Z"
  name: sriovdp-config
  namespace: kube-system
  resourceVersion: "711482"
  selfLink: /api/v1/namespaces/kube-system/configmaps/sriovdp-config
  uid: 8d4991bf-6671-4c85-ba98-6ff33f2d0444
```


> And in the pfName selector of worker-2 config file, should it use PF name instead of PCI addresses?

The worker-2 is a VM and does have only VFs, hence just defined VFs PCI addresses in the pfNames.

**Comment by pperiyasamy** [comment]
> @pperiyasamy how did you apply device plugin config files to different worker nodes? I thought we onlhy support one single config file for the whole cluster.

@zshi-redhat yes, you are correct. Looks like [it](https://github.com/intel/sriov-network-device-plugin/blob/master/cmd/sriovdp/manager.go#L87) just uses config.json of master node (in my case, it's as well as worker-1) for the whole cluster. that's why the devices are visible in both resource pools though it's intended to get added into single resource pool. 
How's sriovdp-config config map used inside device plugin ? Looks it's not used anywhere inside the plugin code. can you explain about it ?

**Comment by pperiyasamy** [comment]
I just had a closer look at sriovdp and it looks sriovdp-daemonset makes config map's config.json content into /etc/pcidp/config.json on the pod, then sriovdp reads the configuration, create ResourceConfig List, discover all host devices, add the devices to resource pool as the config criteria, etc.
But ResourceConfig doesn't have support for adding VF directly into a pool using its PCI addresses (about configuration doesn't work i.e. adding vf pci addresses into pfNames). 
There is a use case where PCI address is the only one unique attribute (sharing same vendor, device and driver names) to create left and right networks for IBD. Do you plan to support it in near future ?

**Comment by pperiyasamy** [comment]
Looks the below fix solves the issue of adding VF PCI addresses into pfNames parameter.

```
$ git diff pkg/resources/pciNetDevice.go
diff --git a/pkg/resources/pciNetDevice.go b/pkg/resources/pciNetDevice.go
index 6e2f15d4..95672ac9 100644
--- a/pkg/resources/pciNetDevice.go
+++ b/pkg/resources/pciNetDevice.go
@@ -59,6 +59,8 @@ func NewPciNetDevice(pciDevice *ghw.PCIDevice, rFactory types.ResourceFactory) (
        pfName, err := utils.GetPfName(pciAddr)
        if err != nil {
                glog.Warningf("unable to get PF name %q", err.Error())
+               // assign pciAddr (VF name in this case) as pfName
+               pfName = pciAddr
        }
        vfID, err := utils.GetVFID(pciAddr)
        if err != nil {
```

**Comment by zshi-redhat** [comment]
> I just had a closer look at sriovdp and it looks sriovdp-daemonset makes config map's config.json content into /etc/pcidp/config.json on the pod, then sriovdp reads the configuration, create ResourceConfig List, discover all host devices, add the devices to resource pool as per config criteria, etc.
> But ResourceConfig doesn't have support for adding VF directly into a pool using its PCI addresses (about configuration doesn't work i.e. adding vf pci addresses into pfNames).
> There is a use case where PCI address is the only one unique attribute (sharing same vendor, device and driver names) to create left and right networks for IBD. Do you plan to support it in near future ?

By `IBD`, do you mean Infiniband device? 
@moshe010 do you see this as a problem when using infiniband device with sriov device plugin?

Regarding infiniband support, I think if the use case is to enable infiniband SR-IOV device, then it should be in the scope of SR-IOV device plugin project. We did talk about having infiniband CNI be supported in the same SR-IOV CNI project in biweekly resource management meeting.

**Comment by pperiyasamy** [comment]
> By `IBD`, do you mean Infiniband device?

This is not Infiniband device. I just meant Image Based Deployments (i.e. k8 worker nodes are VMs). We just create VFs on the baremetal server from a PF (Intel Ethernet Controller XL710 for 40GbE QSFP+) and VFs are attached inside the VM. 
Hence PF info won't be available for these VFs inside the VM and hence sriovdp fails to create device pools with the above resource pool configuration. 
with the above minor fix, the device pool creation looks ok.

**Comment by killianmuldoon** [comment]
@
