### ISSUE TITLE
Question about interplay between sriov-cni, sriov-network-device, multus

### ISSUE THREAD

**Issue by devdattakulkarni** [intel/sriov-network-device-plugin#185]
I was wondering if you could shed light on the exact interactions between sriov-cni plugin, the sriov-network-device plugin and multus plugin.

Based on the README example, here is my understanding of how the three plugins work together. 

sriov-cni: Needs to deployed on each node. It defines deviceIDs (VFs). The config values that need to be defined are closely tied with the capabilities of the underlying node and OS. As such, whoever installs this plugin on each node needs to have this understanding.

sriov-network-device: Needs to be deployed on each node. It defines logical resourceNames. A list of selectors are provided through a ConfigMap which act as a filter to associate the defined resourceName with specific deviceIDs (VFs) available on a node. Note the deviceIDs specified in the selector need to be known to the person configuring this plugin. 

multus: Defines the NetworkAttachmentCRD. When creating a Custom Resource, a resourceName needs to be provided as an annotation. The resourceName has to be one of the names defined in the ConfigMap created when configuring the sriov-network-device plugin. 

Pod: Name of the multus's NetworkAttachment Custom Resource is added as an annotation on it. 

Overall flow is as follows: 

1. Setup: 
    (a) Figure out the VF device ids on each node.
    (b) Run sriov-cni on each node by using the device ids from step (a).
    (c) Run sriov-network-device plugin on each host by defining resourceNames and using
        the device ids from step (a).
    (d) Run multus plugin on the cluster

2. NetworkDefinition:
    (a) Create NetworkAttachment Custom Resource. Use the resourceName defined in 1.c above as an annotation on NetworkAttachment Custom Resource.

3. Pod creation:
    (a) Create Pod with an annotation with NetworkAttachment Custom Resource name in the annotation.

When 3.a is performed, Multus deferences the Custom Resource name to find out the resourceName. It then figures out the deviceID for that resourceName by querying/working with the sriov-network-device plugin. It associates that deviceID to the Pod.

At a high-level is this flow correct?

If so, I have one follow up question. Since the deviceID needs to be specified in the ConfigMap when installing the network device plugin, it means it has to be known to the cluster administrator. If so, what is the exact role of sriov-cni plugin in the overall flow? 

Thanks!

**Comment by zshi-redhat** [comment]
> If so, I have one follow up question. Since the deviceID needs to be specified in the ConfigMap when installing the network device plugin, it means it has to be known to the cluster administrator. If so, what is the exact role of sriov-cni plugin in the overall flow?
> 
Pod requesting SR-IOV resource in its resource request/limit field will be allocated with a device (identified by unique device id) by kubelet, this device id information will be published by kubelet in its endpoint, then be retrieved by Multus which passes down to SR-IOV CNI.
User doesn't need to specifiy the device ID.

**Comment by devdattakulkarni** [comment]
Thanks @zshi-redhat. 

I have couple of more follow up questions, which I have outlined below.

Consider the following configuration snippet:

"resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["154c", "10ed"],
                "drivers": ["i40evf", "ixgbevf"]
         }

- Since a resourceName is associated with a list of devices, in what order are the devices assigned to Pods? Is it in first come first serve basis?
- If for some reason, assignment of first device fails, will sriov-network-device-plugin select the next device in the list and associate that with the Pod?
- What happens when none of the devices in the list are 'available' (by this I mean, say, there are two devices associated with a resourceName and those are already assigned to two Pods. What happens when a third Pod comes along that defines that resourceName in its NetworkAttachment CR?

Related to: https://github.com/intel/multus-cni/issues/425

As a reference to above question, here is the ConfigMap that I am using

**Comment by ahalim-intel** [comment]
> * Since a resourceName is associated with a list of devices, in what order are the devices assigned to Pods? Is it in first come first serve basis?

Kubelet keeps devices in a resource map internally, so devices are selected at random from available devices in resource endpoint. Selection of device is not deterministic.

> * If for some reason, assignment of first device fails, will sriov-network-device-plugin select the next device in the list and associate that with the Pod?

If it fails during device allocation of Pod creation phase Pod will enter into error state in my understanding.

> * What happens when none of the devices in the list are 'available' (by this I mean, say, there are two devices associated with a resourceName and those are already assigned to two Pods. What happens when a third Pod comes along that defines that resourceName in its NetworkAttachment CR?

Like any other allocable resources in Kubernetes, Kube-scheduler will try to find next available node that has sufficient VFs under same resource name to run this Pod. If none found Pod will enter into pending schedule state.

> 
> Related to: [intel/multus-cni#425](https://github.com/intel/multus-cni/issues/425)
> 
> As a reference to above question, here is the ConfigMap that I am using

**Comment by devdattakulkarni** [comment]
Thanks @ahalim-intel for the answers. They are helpful.

I have one more question. When a Pod is deleted, I assume that the associated device is released back to the pool of available devices on that Node. So when another Pod is created afterwards that device can be bound to the new Pod. Is this correct?

**Comment by zshi-redhat** [comment]
> Thanks @ahalim-intel for the answers. They are helpful.
> 
> I have one more question. When a Pod is deleted, I assume that the associated device is released back to the pool of available devices on that Node. So when another Pod is created afterwards that device can be bound to the new Pod. Is this correct?

correct.

**Comment by killianmuldoon** [comment]
closing as stale
