### ISSUE TITLE
make did not build docker image by default Makefile

### ISSUE THREAD

**Issue by xuguozhen** [intel/sriov-network-device-plugin#186]
.PHONY: all
all: fmt lint build
https://github.com/intel/sriov-network-device-plugin/blob/master/Makefile#L49
All did not contain image building,make could not build docker image.

**Comment by zshi-redhat** [comment]
@xuguozhen `make image` should be able to build docker image, `make` only build the binary.

**Comment by killianmuldoon** [comment]
@zshi-redhat I think this is still the appropriate behaviour. Can we close this?
