### ISSUE TITLE
Fail to allocate SRIOV device using Multus and host-device CNI

### ISSUE THREAD

**Issue by meganathanraja** [intel/sriov-network-device-plugin#188]
Hi, 
I have K8 cluster which runs on CentOS 7.7 VMs and then trying to bring up pod with multiple SRIOV interface. The VFs are passthrough into worker VMs. 
Here is my setup details:
1. K8 cluster version : v1.13.4
2. Calico as a default CNI
3. Multus(version 3.2) as CNI meta plugin
4. sriov-device-plugin(version v3.1) device plugin for managing the VFs resources.
5. host-device(version v0.8.3) as CNI plugin  
6. Created configMap for resource list with pf names for sriov hostdevice. 
7. Created CRD by providing the resourceName annotation.

If I use resourceName annotation in the CRD yaml file, the Multus fail to allocate the device from the resource pool and passes it down to host-device CNI plugin. 
Please have a look at the configuration and let me know what's going wrong.
Thanks in advance.
Error message while creating pod:
<pre><code>  [cluster-user@master1vm sriov-multus]$ kubectl describe pod testpod1
Warning  FailedCreatePodSandBox  2s                kubelet, worker1vm.novalocal  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "a58d7fb3a4cc7232f90f727b6a12bf458f3c655b3b5e958a72e7ecd69d70e122" network for pod "testpod1": NetworkPlugin cni failed to set up pod "testpod1_default" network: Multus: Err adding pod to network "host-device-network": Multus: error in invoke Delegate add - "host-device": specify either "device", "hwaddr", "kernelpath" or "pciBusID", failed to clean up sandbox container "a58d7fb3a4cc7232f90f727b6a12bf458f3c655b3b5e958a72e7ecd69d70e122" network for pod "testpod1": NetworkPlugin cni failed to teardown pod "testpod1_default" network: Multus: error in invoke Delegate del - "host-device": specify either "device", "hwaddr", "kernelpath" or "pciBusID"]
</code></pre>

The sriov device plugin identify all the SRIOV device and created the resource pool.
<pre><code>[cluster-user@master1vm sriov-multus]$ kubectl -n kube-system logs kube-sriov-device-plugin-amd64-pbjsp
I1210 23:31:38.945300   22088 manager.go:112] Creating new ResourcePool: intel_sriov_hostdevice
I1210 23:31:38.945328   22088 factory.go:144] device added: [pciAddr: 0000:00:05.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945335   22088 factory.go:144] device added: [pciAddr: 0000:00:09.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945339   22088 factory.go:144] device added: [pciAddr: 0000:00:0a.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945342   22088 factory.go:144] device added: [pciAddr: 0000:00:0b.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945345   22088 factory.go:144] device added: [pciAddr: 0000:00:0c.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945348   22088 factory.go:144] device added: [pciAddr: 0000:00:0d.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945351   22088 factory.go:144] device added: [pciAddr: 0000:00:0e.0, vendor: 8086, device: 10ed, driver: ixgbevf]
I1210 23:31:38.945365   22088 manager.go:125] New resource server is created for intel_sriov_hostdevice ResourcePool
</code></pre>

<pre><code>[cluster-user@master1vm ~]$ kubectl get node worker1vm.novalocal -o json | jq '.status.allocatable'
{
  "cpu": "16",
  "ephemeral-storage": "19316953466",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "intel.com/intel_sriov_dpdk": "0",
  "intel.com/intel_sriov_hostdevice": "7",
  "intel.com/intel_sriov_netdevice": "0",
  "intel.com/mlnx_sriov_rdma": "0",
  "memory": "32676188Ki",
  "pods": "110"
}
</code></pre>

CRD config file
<pre><code>apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_hostdevice
spec:
  config: '{
  "type": "host-device",
  "cniVersion": "0.3.1",
  "name": "host-device-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
</code></pre>

If i configure the device name as part of CRD configuration, pod able to attach additional network interface.
<pre><code>
 config: '{
  "type": "host-device",
  "cniVersion": "0.3.1",
  "name": "host-device-network",
 ** "device": "eth4",**
</code></pre>
Pod config:
<pre><code>
[cluster-user@master1vm sriov-multus]$ cat pod-tc1.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  containers:
    image: master1vm.novalocal:5000/centos/tools:latest 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/intel_sriov_hostdevice: '1'
      limits:
        intel.com/intel_sriov_hostdevice: '1'
</code></pre>

**Comment by killianmuldoon** [comment]
According to [this ](https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device) you need to specify one of device, hwaddr, kernelpath, pciBusID in order to select the correct device. This seems to be reflected in the Multus logs posted above. Once your config - from the network CRD - is passed from multus into the host-device binary it fails with an error and Multus isn't able to provision the network.

**Comment by ahalim-intel** [comment]
@meganathanraja if you have Multus logs that would be helpful.

@zshi-redhat I know you've worked on the host-device cni to enable the "pciBusID" support. Do you have any comment what could be the issue?

**Comment by zshi-redhat** [comment]
> @meganathanraja if you have Multus logs that would be helpful.
> 
> @zshi-redhat I know you've worked on the host-device cni to enable the "pciBusID" support. Do you have any comment what could be the issue?

Hi @ahalim-intel and @meganathanraja, yes, it looks like multus-v3.2 doesn't contain the patch for `pciBusID`, please use v3.3 or above version.

`git describe --contains "91d9964d0730f60e6dfd82dfcad59aaed635f2a8"`   <- the `pciBusID` commit.

**Comment by meganathanraja** [comment]
Thanks all for looking into it.
With the "pciBusID" commit, the Multus able to allocate the device from the resource pool and passes it down to host-device CNI plugin.

**Comment by dromie** [comment]
Other problem could be (just figured this out after several hours), is that the version of host-device could be to old. 
At least 0.8.1 is required.
