### ISSUE TITLE
Make pfNames field in selectors more flexible and support more configurations

### ISSUE THREAD

**Issue by rorysexton** [intel/sriov-network-device-plugin#192]
## What would you like to be added?
I would like to add support to the pfNames field of selectors to allow more resource configurations to be defined.
Currently only an entire PF or contiguous VFs from a PF can be specified by the pfNames selector, only the following syntax is supported:
- "pfNames": ["ens2f1"] - use all VFs of PF ens2f1
- "pfNames": ["ens2f1#0-3"] - use VF's 0-3 of PF ens2f1

I would like to add support to the selector for the following syntax:
- "pfNames": ["ens2f1#0,2-4,7"] - use VF's 0,2-4 and 7 of PF ens2f1
This syntax would support existing syntax so no changes would be required in current configurations in deployment.
It would also enable the selection of any combinations of VFs from a PF into a resource pool which may be desirable.
The only change required would be to the parsing of "pfNames" field in deviceSelectors.go

## What is the use case for this feature / enhancement?
- The use case for this enhancement is to enable more flexible creation of resource pools by the user.
- It may be desirable to select VFs not in a contiguous range to be assigned to same resource pool in certain use cases.
- Such configurations were supported in earlier versions of the sriov device plugin which used entirely different configuration file parameters, this limited syntax has broken support for number of use cases based on earlier versions of sriov device plugin.

Please let me know your opinions on addition of this simple feature to extend plugin capabilities.

**Comment by ahalim-intel** [comment]
Thanks @rorysexton, this sounds like very reasonable usecase and we definitely should look into it.

**Comment by rorysexton** [comment]
This issue can be addressed by this pull request https://github.com/intel/sriov-network-device-plugin/pull/193.

**Comment by zshi-redhat** [comment]
@rorysexton hi thanks for creating the issue and PR!
I'd like to understand in which case will continous range of VF allocation not work? I assume all the VFs provisioned from single PF has the same initial attributes?

**Comment by rorysexton** [comment]
Hi @zshi-redhat,

You're correct in saying that all VFs provisioned from single PF have the same initial attributes.

An example use case would be where alternate VFs are allocated to resource pools for use by Upstream and Downstream workloads. While using a continuous range of VF allocation for Upstream and Downstream would also work, sometimes it is more desirable for the user to use alternate VF allocation. This could be for monitoring reasons of statistics of Upstream and Downstream VFs etc.

So as you said, while VF allocation in continuous range would also work it limits the flexibility of the resource pool. By adding this feature either option would be available to the user.

**Comment by zshi-redhat** [comment]
> Hi @zshi-redhat,
> 
> You're correct in saying that all VFs provisioned from single PF have the same initial attributes.
> 
> An example use case would be where alternate VFs are allocated to resource pools for use by Upstream and Downstream workloads. While using a continuous range of VF allocation for Upstream and Downstream would also work, sometimes it is more desirable for the user to use alternate VF allocation. This could be for monitoring reasons of statistics of Upstream and Downstream VFs etc.
> 

@rorysexton would you mind providing the detailed configs for above upstream/downstream example (using both continous range of VF allocation and this new selecor enhancement). Just trying to understand how this is going to be used in real scenario.

> So as you said, while VF allocation in continuous range would also work it limits the flexibility of the resource pool. By adding this feature either option would be available to the user.

**Comment by zshi-redhat** [comment]
Issue has been addressed by https://github.com/intel/sriov-network-device-plugin/pull/193
