### ISSUE TITLE
Ability to specify MAC address for the VF inside the container

### ISSUE THREAD

**Issue by svallala** [intel/sriov-network-device-plugin#197]
## What would you like to be added?

Ability to provide a way to customize the MAC address for the VF. Other CNI plugins (bridge, macvlan..etc) provide an option to specify the MAC address for an interface within the container by adding "mac" field to the network json.

## What is the use case for this feature / enhancement?

The ability to specify MAC address provides the ability to pre-configure the switch ports to allow traffic from those ports.

**Comment by zshi-redhat** [comment]
Hi @svallala the ability to customize SR-IOV VF MAC address is included in SR-IOV CNI. SR-IOV Device Plugin is only used to discover and expose VF resource to kubelet.
MAC address can be specified in SR-IOV CNI net-attach-def, [here](https://github.com/intel/sriov-cni#main-parameters) is the supported parameters of SR-IOV CNI. However if you want to customize MAC address per each VF device, it may be better to use CNI runtimeConfig, [here](https://github.com/intel/multus-cni/pull/387#issuecomment-540142153) is an example of setting MAC address in Pod annotation per VF device, this config will be parsed by Multus and passed down to SR-IOV CNI which then configures VF device.

**Comment by svallala** [comment]
Thanks @zshi-redhat, I tried both ways of setting up the MAC address for the SRIOV interfaces within the container. Things work fine, for the first time (when the VFs don't have a valid MAC address). When all the VFs are assigned once and they have a valid MAC address, then changing the MAC address when I am deploying again fails.

I see the following errors in multus.log

2020-02-05T10:35:03-08:00 [debug] validateIfName: /proc/5990/ns/net, net1
2020-02-05T10:35:03-08:00 [debug] conflistAdd: &{23b0eeed6d6621fb50047c82ab7c4c0bd4cc96520afcfb2bafae8ac2d5b381d8 /proc/5990/ns/net net1 [[IgnoreUnknown 1] [K8S_POD_NAMESPACE default] [K8S_POD_NAME testpod1] [K8S_POD_INFRA_CONTAINER_ID 23b0eeed6d6621fb50047c82ab7c4c0bd4cc96520afcfb2bafae8ac2d5b381d8]] map[] }, {"cniVersion":"0.3.1","name":"sriov-net1","plugins":[{"deviceID":"0000:01:10.1","mac":"29:33:23:12:13:90","name":"sriov-network","pciBusID":"0000:01:10.1","type":"sriov"},{"capabilities":{"mac":true},"type":"tuning"}]}, /opt/cni/bin
2020-02-05T10:35:03-08:00 [error] conflistAdd: error in getting result from AddNetworkList: SRIOV-CNI failed to configure VF "failed to set MAC address to 29:33:23:12:13:90: invalid argument"
2020-02-05T10:35:03-08:00 [error] delegateAdd: error invoking conflistAdd - "sriov-net1": conflistAdd: error in getting result from AddNetworkList: SRIOV-CNI failed to configure VF "failed to set MAC address to 29:33:23:12:13:90: invalid argument"

Some times I also see an error Operation not permitted.

Here the yaml files I am using

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov0
  creationTimestamp: "2020-02-05T08:33:11Z"
  generation: 6
  name: sriov-net1
  namespace: kube-system
  resourceVersion: "88047"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/kube-system/network-attachment-definitions/sriov-net1
  uid: eeceaa1b-3dd4-4819-b2fa-35b3111762ef
spec:
  config: '{ 
    "cniVersion": "0.3.1",
    "plugins": [ 
        { 
           "type": "sriov",
          "name": "sriov-network",
          "mac": "29:33:23:12:13:90" }, 
          { 
              "capabilities": {"mac": true}, 
              "type": "tuning"
         }
     ] 
  }'

Pod YAML

apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
       {
       "name": "sriov-net1",
       "namespace": "kube-system",
       "ipam": {
         "type": "host-local",
         "subnet": "10.56.217.0/24",
         "routes": [{
           "dst": "0.0.0.0/0"
         }],
         "gateway": "10.56.217.1"
       }
       }
    ]'
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov0: '1'
      limits:
        intel.com/sriov0: '1'

**Comment by svallala** [comment]
Closing this issue. Issue seems to be because of the MAC address that was used. Bit 0 and Bit 1 of the first octet seems to have special meaning and only certain values are valid. Thanks
