### ISSUE TITLE
VF Allocation

### ISSUE THREAD

**Issue by svallala** [intel/sriov-network-device-plugin#198]
### What happened?
Don't see the SRIOV interface within the container. Our platform supports VMs and containers. I had some of the VFs used by the VMs. When I deployed containers, noticed that the container creation goes through fine, but there is no SRIOV interface. Looks like a VF used by VM is assigned to the container.

How does the SRIOV plugin figure out what VF to use?

### What did you expect to happen?
VF allocation should be based on what is exactly available.

**Comment by zshi-redhat** [comment]
Hi @svallala how did you know a VF used by VM is assigned to the container?
SR-IOV device plugin doesn't decide which VF device will be used for which container, it's kubelet that allocate a un-used and healthy device to the container and then calls CNI to move that device into container namespace. If VF allocated to container is in kernel mode, it can be observed by executing `ip link show` inside container. If VF allocated to container is in userspace mode (e.g. vfio-pci), it can be checked by executing `ls /dev/vfio/` (there will be a iommu_group number indicating VF device is inside container).  Also there will be an environment variable with format `PCIDEVICE_**`  containing the PCI address allocated to the contianer.

**Comment by baijuparameswaran** [comment]
> If VF allocated to container is in userspace mode (e.g. vfio-pci), it can be checked by executing `ls /dev/vfio/` (there will be a iommu_group number indicating VF device is inside container). Also there will be an environment variable with format `PCIDEVICE_**` containing the PCI address allocated to the contianer.

when using vfio-pci the container seems to have same view of /dev/vfio as in host is this expected ?

**Comment by svallala** [comment]
Sorry I missed the comments posted earlier. I will try to reproduce the issue again and post the details. Thanks

**Comment by killianmuldoon** [comment]
@svallala  did you manage to reproduce this issue?

**Comment by svallala** [comment]
@killianmuldoon not yet

**Comment by killianmuldoon** [comment]
Closed as stale.
