### ISSUE TITLE
Issue creating an SRIOV interface with custom MAC address

### ISSUE THREAD

**Issue by svallala** [intel/sriov-network-device-plugin#201]
Hi,

    I was hitting issue with Bond CNI, so decided to move to the latest device drivers.

ixgbe - 5.6.5
ixgvevf - 4.6.3

   After updating the drivers I am not able to create even a normal SRIOV pod if MAC address is specified.

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov0
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network"
}'

[root@pocf02 ~]# cat pod-tc1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
       {
       "name": "sriov-net1",
       "namespace": "kube-system",
       "mac": "52:54:00:21:00:94",
       "ipam": {
         "type": "host-local",
         "subnet": "10.56.217.0/24",
         "routes": [{
           "dst": "0.0.0.0/0"
         }],
         "gateway": "10.56.217.1"
       }
       }
    ]'
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov0: '1'
      limits:
        intel.com/sriov0: '1'

Error I see in multus.logs

2020-02-07T12:05:14-08:00 [debug] validateIfName: /proc/15276/ns/net, net1
2020-02-07T12:05:14-08:00 [debug] delegateAdd: set MAC address "52:54:00:21:00:90" to "net1"
2020-02-07T12:05:14-08:00 [error] delegateAdd: error invoking DelegateAdd - "sriov": failed to set up pod interface "net1" from the device "sriov0": failed to set netlink MAC address to 52:54:00:21:00:90: operation not permitted
2020-02-07T12:05:14-08:00 [debug] delPlugins: <nil>, eth0, [0xc0002d54a0 0xc0002d4000 0xc0002d4840 0xc0002d5080], 1, &{2fb4c8ad5687d78a3b58f2027346e69656490a8a244ef3b6a5a53b654b370659 /proc/15276/ns/net net1 [[IgnoreUnknown 1] [K8S_POD_NAMESPACE default] [K8S_POD_NAME test-pod] [K8S_POD_INFRA_CONTAINER_ID 2fb4c8ad5687d78a3b58f2027346e69656490a8a244ef3b6a5a53b654b370659]] map[] }, /opt/cni/bin

Can you please help, once the drivers are updated do I have to anything else? I disabled spoofchk and still hitting the same issue. Earlier I was able to update the MAC address of the VF interface on the host, now I am getting the same error from the host too.

[root@pocf02 ~]# ip link set dev enp1s16f7 addr 52:52:00:fc:9e:90
RTNETLINK answers: Operation not permitted

I reverted back to the original drivers and still hitting the issue. Any pointers would be great help.

**Comment by svallala** [comment]
Another data point, after reloading the VF driver things are working fine, till another change to the MAC address is invoked.

**Comment by zshi-redhat** [comment]
@svallala it looks like the issue has been resolved by reloading VF driver, can we close this issue?

**Comment by zshi-redhat** [comment]
btw, from the issue description, it looks like you have defined `net-attach-def`, but not used in the pod annotation.

**Comment by killianmuldoon** [comment]
closed as stale
