### ISSUE TITLE
Multus fail when geting the delegate cni sriov

### ISSUE THREAD

**Issue by thanhlong9x** [intel/sriov-network-device-plugin#203]
Hi, I'm read and example with your source. I'm run well with cni flannel, but when using sriov I'm get error FailedCreatePodSandBox on pod. In detail, Multus failed geting the delegate cni config from NetworkResource. I'm check all steps from create VF to create net-attach-def sriov but don't find error.
So, I want know what origin for this ?
Thank for watching my issues.
![bug1](https://user-images.githubusercontent.com/29721257/74220315-ddc13200-4ce1-11ea-937b-fdbd588a6a7f.PNG)
![bug2](https://user-images.githubusercontent.com/29721257/74220320-df8af580-4ce1-11ea-9c23-3c107ffe6759.PNG)
![bug3](https://user-images.githubusercontent.com/29721257/74220321-e0238c00-4ce1-11ea-872b-9af01dd3af79.PNG)
![Capture](https://user-images.githubusercontent.com/29721257/74220323-e0bc2280-4ce1-11ea-8a99-a879e07b6a75.PNG)

**Comment by killianmuldoon** [comment]
Hey @thanhlong9x, it looks like you're missing a commoa from your net device CRD, right after "host-local". You can compare to [the example here](https://github.com/intel/sriov-network-device-plugin/blob/master/deployments/sriov-crd.yaml)

Let me know if that solves your issue.

**Comment by thanhlong9x** [comment]
@killianmuldoon thank you but it's not problem. After fix it, nothing change 
![bug5](https://user-images.githubusercontent.com/29721257/74221722-52e23680-4ce5-11ea-8898-48aeb990ce6f.PNG)

**Comment by killianmuldoon** [comment]
Where the output error is "failed to unmarshal" it most likely points to a typo in your network specification. In this case the error says there's an unexpected 'e' somewhere. Can you check your spec again for correct usage of commas and quotation marks? The best reference is the example above.

**Comment by thanhlong9x** [comment]
@killianmuldoon I using your temple and it's working. Maybe I will re-check my file. Thank you
