### ISSUE TITLE
Does sriov support implement pod by Deployment, Daemonset or Statefulset ?  

### ISSUE THREAD

**Issue by thanhlong9x** [intel/sriov-network-device-plugin#210]
Hi, I have a question about sr iov. I read your tutorial and don't see to using deployment, daemonset or statefulset for create pod. I tested with deployment, statefulset but my pods don't have addtional interface (sriov interface). So, I want to know if sr iov have support with them ? and ( if have) How using them ?
Thanks for watching !!!

**Comment by zshi-redhat** [comment]
@thanhlong9x I think it should work with deployment as long as the net-attach-def is correctly configured in pod spec. also there should be sufficient allocatable resource on the node that is larger than deployment replica ( assume ond pod requests one sriov interface/device).

**Comment by thanhlong9x** [comment]
@zshi-redhat yes, I use deployment with minimal conf, just 1 replica and 1 sriov interface/pod. When I describe this pod, request resource is still exist, as below
![image](https://user-images.githubusercontent.com/29721257/75338401-3c310780-58c1-11ea-916e-3557f60be08b.png)

However, interface isn't allocated, as below:
![image](https://user-images.githubusercontent.com/29721257/75338624-9cc04480-58c1-11ea-9b20-03425cb84e6c.png)

**Comment by amorenoz** [comment]
@thanhlong9x Note that the Device Plugin will not add any information to the Annotations. So, unless you use the [SR-IOV CNI ](https://github.com/intel/sriov-cni) in combination with something like Multus, you won't see any additional network information.

**Comment by thanhlong9x** [comment]
@amorenoz  yes, I am using SRIOV in combination with Multus. I fixed my problem. Thank you everybody !
