### ISSUE TITLE
Support pool-specific logic

### ISSUE THREAD

**Issue by amorenoz** [intel/sriov-network-device-plugin#212]
Currently, the SR-IOV Network Device Plugin works under the assumption that all of the `pciNetDevice`'s information can be obtained from its PCI address, independently from what `ResourcePool` it will end up being added to. Hence, no pool-dependent logic can be implemented.

This makes it difficult to use pool options to select what information from the device is given to the pod. As an example of this, `RdmaSpecs` are extracted (or at least tried) for all PciNetDevices but then only returned if the pool has been configured with `isRdma=true`. This is done by externally appending the RdmaSpecs in the only place where pool configuration is easily available, i.e: (rp *resourcePool) GetDeviceSpecs(deviceIDs []string).  This can be seen as suboptimal and a non-intuitive way of working around the above-mentioned assumption.

## What would you like to be added?

A clear way of adding pool-specific logic, either at runtime or at discovery-time.

### Option 1: Logic at runtime

If runtime logic was prefered, a new function (i.e: `Allocate()`) could be added to `PciNetDevice` and called (with the pool's configuration info) before retrieving the device's information. That way, we would have a unified way of modifying the device specs on a per-pool basis (instead of an ad hoc solution for rdma devices).

Another option would be to add the pool's configuration to the current 'get' functions (`GetDeviceSpecs()`, `GetMounts()`, etc).

### Option 2: Logic at discovery time

If runtime logic is to be avoided to minimize the potential performance impact, we could split the current PciNetDevice into two interfaces. PciNetDevice would continue to server low-level device data, and a new interface (e.g: PoolDevice) would serve the information that the ResourcePool really needs. 
For example:

```
// PciNetDevice provides an interface to get network device specific information. Used for filtering and pool assignment
type PciNetDevice interface {
	GetPFName() string
	GetPfPciAddr() string
	GetVendor() string
	GetDriver() string
	GetDeviceCode() string
	GetPciAddr() string
	GetNetName() string
	IsSriovPF() bool
	GetLinkSpeed() string
	GetLinkType() string
	GetSubClass() string
	GetRdmaSpec() RdmaSpec
	GetVFID() int
	GetDDPProfiles() string
}

// PoolDevice provides an interface to get the information that will be used by the ResourcePool
type PoolDevice interface {
	GetDeviceSpecs() []*pluginapi.DeviceSpec
	GetEnvVal() string
	GetMounts() []*pluginapi.Mount
	GetAPIDevice() *pluginapi.Device
}
```

That way, a PoolDevice instance could be created when the devices are added to a pool combining resource and device information. 
Example:

```
// GetResourcePool returns an instance of resourcePool
func (rf *resourceFactory) GetResourcePool(rc *types.ResourceConfig, filteredDevice []types.PciNetDevice) (types.ResourcePool, error) {

	devicePool := make(map[string]types.PoolDevice, 0)
	apiDevices := make(map[string]*pluginapi.Device)
	for _, dev := range filteredDevice {
		pciAddr := dev.GetPciAddr()
		poolDev, err := newPciNetPoolDevice(dev, rc, rf) // This will combine device and pool information and provide a struct that implements PoolDevice
    [...]
```

## What is the use case for this feature / enhancement?

The immediate benefit of this enhancement would be to clean up the rdma-core specific logic from the pool's GetDeviceSpecs.

In addition, some devices could have multiples ways of being exposed to the pod and pool-specific options could be used to select between then. This is the case of DPDK-based vDPA devices.

These devices are usually bound to normal vfio/rdma drivers and can be exposed as standard SR-IOV devices or as a vDPA device (with the help of a vDPA Daemon that translates the control plane and exposes a vhost interface). It's up to the user to select between both and this cannot be determined by the device information itself.

In this case, we would need to create a new `DeviceInfoProvider` and select it based on a pool configuration option. This is not possible now but very easy with this enhancement.

All this would also be possible with #208 but I'm starting this discussion in the hope an easier, shorter approach is considered acceptable.

**Comment by ahalim-intel** [comment]
Hi @amorenoz I'm currently working on an implementation as per discussion in #208. I believe some of the changes coming down the line will make it easier to have pool specific logic to be implemented. Please keep an eye PR related to that. If it doesn't solve the problem you're discussing here then do propose what changes are necessary.

**Comment by amorenoz** [comment]
Hi @ahalim-intel I think that #208 could offer a solution. But since it is a much broader discussion I wanted to open the discussion for a smaller rework that could achieve just that.

To clarify my point I've prepared #213 and a sample vdpa implementation based on that can be seen [here](https://github.com/amorenoz/sriov-network-device-plugin/commit/78fbe6a7e287a072e38c597fd7e4ba874ebeac7f)

If you prefer to have this feature included in #208 that's fine with me as well.

**Comment by ahalim-intel** [comment]
Both proposed changes involve refactoring and redefining some common interfaces. It's better to do this in one place IMO.
If it doesn't sail through then we can definitely consider this proposal and related PR.

**Comment by zshi-redhat** [comment]
> ### Option 1: Logic at runtime
> ### Option 2: Logic at discovery time

I'd prefer option 1 if device spec can be determined before hand or it's static after device creation or driver binding.  but if there is possibility that device spec may be changed on the fly, then we would consider adding it in runtime. I think device plugin is implemented to be light-weight that can be easily restarted to discover device changes and there is no logic in device plugin to dynamically discover devices.

**Comment by zshi-redhat** [comment]
> Hi @amorenoz I'm currently working on an implementation as per discussion in #208. I believe some of the changes coming down the line will make it easier to have pool specific logic to be implemented. Please keep an eye PR related to that. If it doesn't solve the problem you're discussing here then do propose what changes are necessary.

I can see the problem described in this proposal is slightly different from #208 which aims to provide generic framework for all types of devices. This one is more to separate common PCI (net) device property discovey from device spec used when allocating devices, which could also be applied to other types of devices. This might be an addon improvement after device type.

**Comment by amorenoz** [comment]
> Both proposed changes involve refactoring and redefining some common interfaces. It's better to do this in one place IMO.
> If it doesn't sail through then we can definitely consider this proposal and related PR.

Makes sense


>>    Option 1: Logic at runtime
>>    Option 2: Logic at discovery time

>I'd prefer option 1 if device spec can be determined before hand or it's static after device creation or driver binding. but if there is possibility that device spec may be changed on the fly, then we would consider adding it in runtime. I think device plugin is implemented to be light-weight that can be easily restarted to discover device changes and there is currently no logic in device plugin to dynamically discover devices.

By your arguments, it seems you prefer "Option 2: Logic at discovery time". Is that right?

**Comment by zshi-redhat** [comment]
> > I'd prefer option 1 if device spec can be determined before hand or it's static after device creation or driver binding. but if there is possibility that device spec may be changed on the fly, then we would consider adding it in runtime. I think device plugin is implemented to be light-weight that can be easily restarted to discover device changes and there is currently no logic in device plugin to dynamically discover devices.
> 
> By your arguments, it seems you prefer "Option 2: Logic at discovery time". Is that right?

Yes, sorry for the mistake, I was thinking 2, but put the wrong number there.

**Comment by ahalim-intel** [comment]
> > Hi @amorenoz I'm currently working on an implementation as per discussion in #208. I believe some of the changes coming down the line will make it easier to have pool specific logic to be implemented. Please keep an eye PR related to that. If it doesn't solve the problem you're discussing here then do propose what changes are necessary.
> 
> I can see the problem described in this proposal is slightly different from #208 which aims to provide generic framework for all types of devices. This one is more to separate common PCI (net) device property discovey from device spec used when allocating devices, which could also be applied to other types of devices. This might be an addon improvement after device type.

I agree , the problem described here is slightly different but if you look closely the proposed changes in terms of extracting a new interface from 'PciNetDevice' a new interface 'PoolDevice' is also covered in other proposal.

**Comment by zshi-redhat** [comment]
> > > Hi @amorenoz I'm currently working on an implementation as per discussion in #208. I believe some of the changes coming down the line will make it easier to have pool specific logic to be implemented. Please keep an eye PR related to that. If it doesn't solve the problem you're discussing here then do propose what changes are necessary.
> > 
> > 
> > I can see the problem described in this proposal is slightly different from #208 which aims to provide generic framework for all types of devices. This one is more to separate common PCI (net) device property discovey from device spec used when allocating devices, which could also be applied to other types of devices. This might be an addon improvement after device type.
> 
> I agree , the problem described here is slightly different but if you look closely the proposed changes in terms of extracting a new interface from 'PciNetDevice' a new interface 'PoolDevice' is also covered in other proposal.

If considering `PciNetDevice` to be an extracted structure from `PciDevice`, I understand `PicNetDevice` will the `PoolDevice` new interface you mentioned above that contains device spec used for allocation?
