### ISSUE TITLE
daemonset to launch the plugin

### ISSUE THREAD

**Issue by krsna1729** [intel/sriov-network-device-plugin#22]
It would help users if a daemonset with the necessary RBAC enabled for sriov-device plugin (and multus) as shown here -

https://github.com/amshinde/kata-sriov-dp/blob/master/sriov-daemon.yaml

**Comment by rkamudhan** [comment]
Thanks for suggestions krishna. Multus as own daemonset. After the version release, we have to consider this feature. Really appreciate your suggestions.
