### ISSUE TITLE
is there a way to avoid repeating pod annotation to attach multiple devices of same type?

### ISSUE THREAD

**Issue by blackgold** [intel/sriov-network-device-plugin#220]
## What issue would you like to bring attention to?
Following is configuration I am working with

**device plugin exposing multiple devices**
apiVersion: v1
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_sriov_rdma",
                "resourcePrefix": "intel.com",
                "isRdma": true,
                "selectors": {
                    "pfNames": ["enp5s0#0-0", "enp12s0#0-0", "enp132s0#0-0", "enp139s0#0-0"]
                }
            }
        ]
    }
kind: ConfigMap

**Verify kubelet is exposing the devices**
Capacity:
  cpu:                         80
  ephemeral-storage:           459426920Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  intel.com/mlnx_sriov_rdma:   4
  memory:                      528264868Ki
  pods:                        110
Allocatable:
  cpu:                         79900m
  ephemeral-storage:           423407848771
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  intel.com/mlnx_sriov_rdma:   4
  memory:                      527912468Ki
  pods:                        110

**Add a  NetworkAttachmentDefinition**
$ kubectl get network-attachment-definitions -n kube-system sriov-net -o yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma
   name: sriov-net
  namespace: kube-system
  spec:
  config: '{ "type": "sriov", "cniVersion": "0.3.1", "name": "sriov-network", "delegates":
    [ { "cniVersion": "0.3.1", "type": "sbr", "name": "sbr" } ] }'

**Submit a pod with 2 rdma resources.**
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/sriov-net,kube-system/sriov-net
  name: test
spec:
  containers:
  - name: "test"
    command: [ "/bin/bash", "-c", "sleep 3600" ]
    image: ubuntu:latest
    resources:
      limits:
        cpu: "1"
        intel.com/mlnx_sriov_rdma: "2"
        memory: "42949600"
      requests:
        cpu: "1"
        intel.com/mlnx_sriov_rdma: "2"
        memory: "42949600"  

**Is there a way to avoid repeating the kube-system/sriov-net annotation in pod spec?**

## What is the impact of this issue?
No impact as such. However it seems the device count is repeated both in annotation and pod resource spec.

## Do you have a proposed response or remediation for the issue?
I want to understand if I am doing this correct.

**Comment by zshi-redhat** [comment]
> 
> **Is there a way to avoid repeating the kube-system/sriov-net annotation in pod spec?**

nope afaik.

> ## Do you have a proposed response or remediation for the issue?

[network-resources-injector](https://github.com/intel/network-resources-injector) project does automatic injection of resource name into pod spec according to resource name in net-attach-def.

**Comment by blackgold** [comment]
@zshi-redhat  just curious why its not other way around. 
Based on the device resources, the Multus can interpret how many devices it needs to attach to pod. 
Is this a question to Multus project?

**Comment by zshi-redhat** [comment]
> @zshi-redhat just curious why its not other way around.
> Based on the device resources, the Multus can interpret how many devices it needs to attach to pod.

This is related to how NPWG(Networking Plumbing Working Group) defines net-attach-def format.
As normally one network(defined in one net-attach-def) is applied to one type of resource, not two or more. If there are multiple resource names available in cluster, user will need to define different net-attach-def even if the only difference in the net-attach-def is resource name annotation.

> Is this a question to Multus project?

Yes, this(the use of resource name in net-attach-def) is defined in NPWG spec (not standardized yet), multus is one of the implementationso f NPWG spec.

**Comment by mukesh-dua** [comment]
One might be able to solve an example use case shown here but it might create concerns when you want to create multiple interfaces that belongs to different resource names. 
Take an example use case where you would need to attach 5 interface resources: Say 2 resources belonging to resource_A, 1 to resource_B and then 2 belonging to resource_C

**Comment by killianmuldoon** [comment]
Closing as stale
