### ISSUE TITLE
make clean fails: rm: cannot remove ... Permission denied

### ISSUE THREAD

**Issue by amorenoz** [intel/sriov-network-device-plugin#232]
### What happened?

`make clean` no longer works. A long list of logs like this is shown:
`rm: cannot remove '.../sriov-network-device-plugin/.gopath/pkg/mod/golang.org/x/net@v0.0.0-20200324143707-d3edc9973b7e/route/interface_multicast.go': Permission denied`  

Probably due to the recent switch to "go mod" (#225 )

### What did you expect to happen?

`make clean` should work

### What are the minimal steps needed to reproduce the bug?

`make; make clean`

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |master|

**Comment by zshi-redhat** [comment]
@amorenoz I can reproduce this issue when build/clean with GO111MODULE=on && non-root user.
It seems that we need to explicitly clean up the build cache in order to remove the `.gopath/pkg/mod` directory.

**Comment by amorenoz** [comment]
@zshi-redhat Did you look at my PR  #233 ?

**Comment by amorenoz** [comment]
Oh, you just posted the exact same one :)

**Comment by zshi-redhat** [comment]
> @zshi-redhat Did you look at my PR #233 ?

Sorry, I didn't notice that

**Comment by zshi-redhat** [comment]
> Oh, you just posted the exact same one :)

Let's use yours.
