### ISSUE TITLE
Which type to use for VFs attached to a VM "sriov" or "host-device"?

### ISSUE THREAD

**Issue by sacckth** [intel/sriov-network-device-plugin#236]
## What issue would you like to bring attention to?
In my setup, built on top of Openstack, the VMs have VFs attached. I am trying to use a NetworkAttachmentDefinition with type "SRIOV" but , after deploying a test pod it fails to be created still with the following message:
`1s Warning FailedCreatePodSandBox pod/testpod1 Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "d3cf466f8473ff0c21f23891d522758844de90fbbdb22b50473264ebe356bb94" network for pod "testpod1": networkPlugin cni failed to set up pod "testpod1_default" network: Multus: [default/testpod1]: error adding container to network "sriov-network": delegateAdd: error invoking DelegateAdd - "sriov": error in getting result from AddNetwork: SRIOV-CNI failed to load netconf: LoadConf(): failed to get VF information: "lstat /sys/bus/pci/devices/0000:00:07.0/physfn/net: no such file or directory", failed to clean up sandbox container "d3cf466f8473ff0c21f23891d522758844de90fbbdb22b50473264ebe356bb94" network for pod "testpod1": networkPlugin cni failed to teardown pod "testpod1_default" network: delegateDel: error invoking DelegateDel - "sriov": error in getting result from DelNetwork: error reading cached NetConf in /var/lib/cni/sriov with name d3cf466f8473ff0c21f23891d522758844de90fbbdb22b50473264ebe356bb94-net1]`

My config.json
`{ "resourceName": "mlnx_sriov_core", "sriovMode": false, "selectors": { "vendors": ["15b3"], "devices": ["1016"], "drivers": ["mlx5_core"] } }
`
NetworkAttachmentDefinition:
`--- apiVersion: "k8s.cni.cncf.io/v1" kind: NetworkAttachmentDefinition metadata: name: sriov-net1 annotations: k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_core spec: config: '{ "type": "sriov", "cniVersion": "0.3.1", "name": "sriov-network", "ipam": { "type": "host-local", "subnet": "10.56.217.0/24", "routes": [{ "dst": "0.0.0.0/0" }], "gateway": "10.56.217.1" } }'
`
## What is the impact of this issue?
I'm just trying to understand whether I can use a NetworkAttachmentDefinition with type "sriov" for this case or I have to use type "host-device"

**Comment by killianmuldoon** [comment]
I think the host device plugin should suit your use case here - is there a reason you want to use the sriov plugin?

**Comment by sacckth** [comment]
> I think the host device plugin should suit your use case here - is there a reason you want to use the sriov plugin?

Thanks for the prompt answer.  Well, host-device let me do what I intend so far. i just think it could be handy to use the VFs in the VM from a resource pool instead of defining a networkAttachmentDefinition for each VF.

**Comment by ahalim-intel** [comment]
This is a CNI plugin related issue and there is a [PR ](https://github.com/intel/sriov-cni/pull/121)for sriov-cni for this use case which is under review.

**Comment by sacckth** [comment]
> This is a CNI plugin related issue and there is a [PR ](https://github.com/intel/sriov-cni/pull/121)for sriov-cni for this use case which is under review.

Thanks I will checkout the pull request locally!
