### ISSUE TITLE
Is it possible to create an SRIOV interface with custom MAC address inside Pod?

### ISSUE THREAD

**Issue by PrahladaHerle** [intel/sriov-network-device-plugin#241]
Is it possible to create an SRIOV interface with custom MAC address inside Pod?
Is there any specific syntax in Pod definition?
Is there any restriction to mac address values?

I was testing with following configuration. I have attached pod definition and related files. I am facing issue where in worker node is rebooting when i start the Pod.
OS: CentOS-7
Kernel: 3.10.0-rt56 (realtime kernel)
Docker: 19.03.11
Kubernetes: v1.18.3
Ethernet card info: 3b:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ [8086:1583] (rev 02)
Using Multus/SR-IOV device plugin

![image](https://user-images.githubusercontent.com/13450401/84149147-9d9a7200-aa7d-11ea-8604-9ceb288a6280.png)

![image](https://user-images.githubusercontent.com/13450401/84149260-cd497a00-aa7d-11ea-934c-fe223deb5057.png)

[syslog.txt](https://github.com/intel/sriov-network-device-plugin/files/4752177/syslog.txt)

**Comment by killianmuldoon** [comment]
This is likely an issue with the driver kernel rather than with the sriov device plugin. Can you get the version of the NIC driver being used? ( ethtool -i <PF_NAME> )

**Comment by PrahladaHerle** [comment]
# ethtool -i p2p2
driver: i40e
version: 2.9.21
firmware-version: 6.80 0x80003d1a 18.8.9
expansion-rom-version: 
bus-info: 0000:3b:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

**Comment by killianmuldoon** [comment]
Can you try to do this with "spoofchk": "off", set in the network attachment definition? Alternatively, as this looks to be a driver issue, you could update your VF driver to the [iavf driver](https://downloadcenter.intel.com/download/24693/Intel-Network-Adapter-Virtual-Function-Driver-for-Intel-Ethernet-Controller-700-Series).

**Comment by killianmuldoon** [comment]
Compare with https://github.com/intel/sriov-cni/issues/106

**Comment by PrahladaHerle** [comment]
Sure .. will try suggested changes ... and update
Not sure if I am allowed to change the driver (have to get permission in the organization), will try my best

**Comment by killianmuldoon** [comment]
@PrahladaHerle have you any updates on this?

**Comment by killianmuldoon** [comment]
Closing as stale.
