### ISSUE TITLE
timeout while getting ddptool in make image

### ISSUE THREAD

**Issue by AbdYsn** [intel/sriov-network-device-plugin#247]
## What issue would you like to bring attention to?

when `make image` is performed, sometimes it fails to get the ddptools from the source. see error [1]. This happens occasionally, and when it happens, even if wget is used, it will timeout. so it seams to be an issue with the server. There is no set time to reproduce this, but it started to pop up enough times that it is noticeable (almost every other day).
[1] 
00:33:06 Step 1/14 : FROM golang:alpine as builder
00:33:06  ---> 3289bf11c284
00:33:06 Step 2/14 : ADD . /usr/src/sriov-network-device-plugin
00:33:29  ---> df4b5dc2865a
00:33:29 Step 3/14 : ADD https://downloads.sourceforge.net/project/e1000/ddptool%20stable/ddptool-1.0.0.0/ddptool-1.0.0.0.tar.gz /tmp/ddptool/
00:33:43 ADD failed: Get https://tenet.dl.sourceforge.net/project/e1000/ddptool%20stable/ddptool-1.0.0.0/ddptool-1.0.0.0.tar.gz: net/http: TLS handshake timeout
00:33:43 make: *** [image] Error 1  

## What is the impact of this issue?

Failing to build the docker image.

## Do you have a proposed response or remediation for the issue?

**Comment by AbdYsn** [comment]
@adrianchiris

**Comment by adrianchiris** [comment]
@ahalim-intel , have you encountered the issue ? This occasionally breaks Mellanox CI.

**Comment by martinkennelly** [comment]
I have seen this on our internal CI. 
I thought it was due to a bad default mirror. Others were having this issue with this mirror provider as well. This mirror was demoted on sourceforge but it seems it did not solve the issue.

**Comment by killianmuldoon** [comment]
Fixed by #246
