### ISSUE TITLE
Failed to build image because of ADD

### ISSUE THREAD

**Issue by AbdYsn** [intel/sriov-network-device-plugin#248]
### What happened?

Failed to build the docker image on step 6 with error `tar: invalid magic, tar: short read`. see [1]. The issue seams to be with the ddptool package being corrupted. Tried to look more into the issue: 
 - when the package is downloaded manually, then either `COPY`, or `ADD` is used, the build succeed.
 - When `RUN`  is used with `wget -P` instead of `ADD`, the build succeed.

Not sure why the issue started to show up recently, but it is happening every day since jun 13. 

This seams related to #246. 

### What did you expect to happen?

The image build to succeed.

### What are the minimal steps needed to reproduce the bug?

- clone the project.
- make image

### Anything else we need to know?

This happens on different OSes (was seen on CENTOS 7.7, and UBUNTU 18.04). and with different docker versions (tested on v18.09.7, and v19.03.11).

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

### Logs

[1]

[1]
11:49:41 + make image
11:49:41 Building Docker image...
11:49:44 Sending build context to Docker daemon  230.7MB

11:49:44 Step 1/14 : FROM golang:alpine as builder
11:49:44  ---> 3289bf11c284
11:49:44 Step 2/14 : ADD . /usr/src/sriov-network-device-plugin
11:50:09  ---> 9fd081c065a0
11:50:09 Step 3/14 : ADD https://downloads.sourceforge.net/project/e1000/ddptool%20stable/ddptool-1.0.0.0/ddptool-1.0.0.0.tar.gz /tmp/ddptool/
11:50:12 
11:50:14  ---> eb89df4a3705
11:50:14 Step 4/14 : ENV HTTP_PROXY $http_proxy
11:50:14  ---> Running in 574d2da8214f
11:50:15 Removing intermediate container 574d2da8214f
11:50:15  ---> 87251318195e
11:50:15 Step 5/14 : ENV HTTPS_PROXY $https_proxy
11:50:15  ---> Running in 71b587943810
11:50:16 Removing intermediate container 71b587943810
11:50:16  ---> 6ee062f102ac
11:50:16 Step 6/14 : RUN apk add --update --virtual build-dependencies build-base linux-headers &&     cd /usr/src/sriov-network-device-plugin &&     make clean &&     make build &&     cd /tmp/ddptool && tar zxvf ddptool-1.0.0.0.tar.gz && make
11:50:16  ---> Running in 108a00842caa
11:50:17 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
11:50:18 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
11:50:19 (1/23) Upgrading musl (1.1.24-r8 -> 1.1.24-r9)
11:50:19 (2/23) Installing libgcc (9.3.0-r2)
11:50:19 (3/23) Installing libstdc++ (9.3.0-r2)
11:50:19 (4/23) Installing binutils (2.34-r1)
11:50:20 (5/23) Installing libmagic (5.38-r0)
11:50:20 (6/23) Installing file (5.38-r0)
11:50:20 (7/23) Installing gmp (6.2.0-r0)
11:50:20 (8/23) Installing isl (0.18-r0)
11:50:21 (9/23) Installing libgomp (9.3.0-r2)
11:50:21 (10/23) Installing libatomic (9.3.0-r2)
11:50:21 (11/23) Installing libgphobos (9.3.0-r2)
11:50:21 (12/23) Installing mpfr4 (4.0.2-r4)
11:50:21 (13/23) Installing mpc1 (1.1.0-r1)
11:50:21 (14/23) Installing gcc (9.3.0-r2)
11:50:28 (15/23) Installing musl-dev (1.1.24-r9)
11:50:29 (16/23) Installing libc-dev (0.7.2-r3)
11:50:29 (17/23) Installing g++ (9.3.0-r2)
11:50:34 (18/23) Installing make (4.3-r0)
11:50:34 (19/23) Installing fortify-headers (1.1-r0)
11:50:34 (20/23) Installing patch (2.7.6-r6)
11:50:34 (21/23) Installing build-base (0.5-r2)
11:50:34 (22/23) Installing linux-headers (5.4.5-r1)
11:50:34 (23/23) Installing build-dependencies (20200621.085019)
11:50:34 Executing busybox-1.31.1-r16.trigger
11:50:34 OK: 213 MiB in 37 packages
11:50:35 Cleaning...
11:50:35 setting GOPATH...
11:50:41 [91mgo: downloading github.com/jaypipes/ghw v0.6.0
11:50:41 go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
11:50:41 [0m[91mgo: downloading k8s.io/kubelet v0.18.1
11:50:41 [0m[91mgo: downloading github.com/vishvananda/netlink v1.1.0
11:50:41 [0m[91mgo: downloading github.com/pkg/errors v0.9.1
11:50:41 [0m[91mgo: downloading google.golang.org/grpc v1.28.1
11:50:41 [0m[91mgo: downloading github.com/Mellanox/rdmamap v1.0.0
11:50:41 go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
11:50:41 [0m[91mgo: downloading github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
11:50:42 [0m[91mgo: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
11:50:42 [0m[91mgo: downloading github.com/gogo/protobuf v1.3.1
11:50:42 [0m[91mgo: downloading github.com/ghodss/yaml v1.0.0
11:50:42 [0m[91mgo: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
11:50:43 [0m[91mgo: downloading github.com/golang/protobuf v1.3.3
11:50:43 [0m[91mgo: downloading github.com/jaypipes/pcidb v0.5.0
11:50:43 [0m[91mgo: downloading gopkg.in/yaml.v2 v2.2.8
11:50:44 [0m[91mgo: downloading golang.org/x/text v0.3.2
11:50:44 [0m[91mgo: downloading github.com/mitchellh/go-homedir v1.0.0
11:50:44 [0m[91mgoogle.golang.org/grpc/serviceconfig
11:50:49 [0m[91mgoogle.golang.org/grpc/internal/grpclog
11:50:49 [0m[91mgoogle.golang.org/grpc/internal/grpcsync
11:50:50 google.golang.org/grpc/internal/buffer
11:50:50 [0m[91mgithub.com/gogo/protobuf/sortkeys
11:50:50 [0m[91mgoogle.golang.org/grpc/encoding
11:50:50 [0m[91mgolang.org/x/text/transform
11:50:50 [0m[91mgoogle.golang.org/grpc/backoff
11:50:50 google.golang.org/grpc/internal/grpcrand
11:50:50 [0m[91mgoogle.golang.org/grpc/keepalive
11:50:50 [0m[91mgoogle.golang.org/grpc/tap
11:50:50 [0m[91mgolang.org/x/net/context
11:50:50 [0m[91mgoogle.golang.org/grpc/internal/envconfig
11:50:50 [0m[91mgithub.com/mitchellh/go-homedir
11:50:50 [0m[91mos/user
11:50:50 [0m[91mgoogle.golang.org/grpc/grpclog
11:50:50 [0m[91mgolang.org/x/net/internal/timeseries
11:50:50 [0m[91mgopkg.in/yaml.v2
11:50:50 [0m[91mgolang.org/x/sys/unix
11:50:50 [0m[91mnet
11:50:50 google.golang.org/grpc/attributes
11:50:50 [0m[91mgoogle.golang.org/grpc/codes
11:50:50 [0m[91mgolang.org/x/text/unicode/bidi
11:50:50 [0m[91mgithub.com/vishvananda/netns
11:50:50 [0m[91mgithub.com/pkg/errors
11:50:50 [0m[91mgoogle.golang.org/grpc/metadata
11:50:50 [0m[91mgithub.com/golang/protobuf/proto
11:50:50 [0m[91mgoogle.golang.org/grpc/internal/backoff
11:50:50 [0m[91mgolang.org/x/net/http2/hpack
11:50:50 [0m[91mgithub.com/gogo/protobuf/proto
11:50:50 [0m[91mgolang.org/x/text/unicode/norm
11:50:50 [0m[91mgoogle.golang.org/grpc/connectivity
11:50:50 [0m[91mgoogle.golang.org/grpc/internal/balancerload
11:50:50 [0m[91mgithub.com/golang/glog
11:50:50 [0m[91mgoogle.golang.org/grpc/internal
11:50:50 [0m[91mgolang.org/x/text/secure/bidirule
11:50:50 [0m[91mgolang.org/x/net/idna
11:50:50 [0m[91mgithub.com/ghodss/yaml
11:50:50 [0m[91mgoogle.golang.org/grpc/credentials/internal
11:50:50 google.golang.org/grpc/internal/syscall
11:50:50 vendor/golang.org/x/net/http/httpproxy
11:50:50 [0m[91mgoogle.golang.org/grpc/stats
11:50:50 google.golang.org/grpc/naming
11:50:50 [0m[91mnet/textproto
11:50:50 [0m[91mgithub.com/vishvananda/netlink/nl
11:50:50 [0m[91mcrypto/x509
11:50:50 [0m[91mgithub.com/golang/protobuf/ptypes/duration
11:50:50 [0m[91mgithub.com/golang/protobuf/ptypes/timestamp
11:50:50 [0m[91mgoogle.golang.org/grpc/encoding/proto
11:50:50 [0m[91mgithub.com/golang/protobuf/ptypes/any
11:50:50 [0m[91mgoogle.golang.org/grpc/binarylog/grpc_binarylog_v1
11:50:50 [0m[91mgoogle.golang.org/genproto/googleapis/rpc/status
11:50:51 [0m[91mgithub.com/golang/protobuf/ptypes
11:50:51 [0m[91mgolang.org/x/net/http/httpguts
11:50:51 [0m[91mvendor/golang.org/x/net/http/httpguts
11:50:51 [0m[91mgoogle.golang.org/grpc/status
11:50:51 [0m[91mgoogle.golang.org/grpc/internal/binarylog
11:50:51 [0m[91mgithub.com/vishvananda/netlink
11:50:51 [0m[91mcrypto/tls
11:50:51 [0m[91mgithub.com/gogo/protobuf/protoc-gen-gogo/descriptor
11:50:51 [0m[91mgithub.com/gogo/protobuf/gogoproto
11:50:51 [0m[91mnet/http/httptrace
11:50:51 [0m[91mgoogle.golang.org/grpc/credentials
11:50:51 [0m[91mnet/http
11:50:51 [0m[91mgoogle.golang.org/grpc/peer
11:50:52 google.golang.org/grpc/resolver
11:50:52 [0m[91mgoogle.golang.org/grpc/internal/channelz
11:50:52 [0m[91mgoogle.golang.org/grpc/internal/grpcutil
11:50:52 google.golang.org/grpc/balancer
11:50:52 [0m[91mgoogle.golang.org/grpc/internal/resolver/passthrough
11:50:52 [0m[91mgoogle.golang.org/grpc/internal/resolver/dns
11:50:52 [0m[91mgoogle.golang.org/grpc/balancer/base
11:50:52 [0m[91mgoogle.golang.org/grpc/balancer/roundrobin
11:50:52 [0m[91mgithub.com/Mellanox/rdmamap
11:50:52 github.com/intel/sriov-network-device-plugin/pkg/utils
11:50:52 [0m[91mgithub.com/jaypipes/pcidb
11:50:53 [0m[91mgolang.org/x/net/trace
11:50:53 net/http/httputil
11:50:53 [0m[91mgolang.org/x/net/http2
11:50:53 [0m[91mgithub.com/jaypipes/ghw
11:50:53 [0m[91mgoogle.golang.org/grpc/internal/transport
11:50:53 [0m[91mgoogle.golang.org/grpc
11:50:54 [0m[91mk8s.io/kubelet/pkg/apis/pluginregistration/v1
11:50:54 [0m[91mk8s.io/kubelet/pkg/apis/deviceplugin/v1beta1
11:50:54 [0m[91mgithub.com/intel/sriov-network-device-plugin/pkg/types
11:50:55 [0m[91mgithub.com/intel/sriov-network-device-plugin/pkg/resources
11:50:55 [0m[91mgithub.com/intel/sriov-network-device-plugin/pkg/accelerator
11:50:55 [0m[91mgithub.com/intel/sriov-network-device-plugin/pkg/netdevice
11:50:55 [0m[91mgithub.com/intel/sriov-network-device-plugin/pkg/factory
11:50:55 [0m[91mgithub.com/intel/sriov-network-device-plugin/cmd/sriovdp
11:50:55 [0mBuilding sriovdp...
11:50:58 Done!
11:50:58 [91mtar: invalid magic
11:50:58 [0m[91mtar: short read
11:50:58 [0mThe command '/bin/sh -c apk add --update --virtual build-dependencies build-base linux-headers &&     cd /usr/src/sriov-network-device-plugin &&     make clean &&     make build &&     cd /tmp/ddptool && tar zxvf ddptool-1.0.0.0.tar.gz && make' returned a non-zero code: 1
11:50:59 Makefile:149: recipe for target 'image' failed
11:50:59 make: *** [image] Error 1

**Comment by AbdYsn** [comment]
@adrianchiris

**Comment by killianmuldoon** [comment]
Fixed by #246
