### ISSUE TITLE
Help to integrate sriov-device-plugin with multus in GKE (google cloud kubernetes engine)

### ISSUE THREAD

**Issue by ravikumar1907** [intel/sriov-network-device-plugin#249]
I configured/deployed sriov-cni in Google's Kubernetes Engine as mentioned here https://github.com/intel/sriov-network-device-plugin#deploy-the-device-plugin
But it seems sriov is not be configure/find resources in GKE node.
I did the below steps in sequence.

# Create ConfigMap
$ kubectl create -f deployments/configMap.yaml
# Create sriov-device-plugin-daemonset
$ kubectl create -f deployments/k8s-v1.16/sriovdp-daemonset.yaml
$kubectl create -f multus-cni/images/multus-daemonset-gke-1.16.yml
$kubectl create -f sriov-network-device-plugin/deployments/sriov-crd.yaml

After create a sample pod-tc1.yaml which is always in pending state with below error.
**Warning  FailedScheduling  11s (x2 over 11s)  default-scheduler  0/1 nodes are available: 1 Insufficient intel.com/intel_sriov_netdevice**

$ kubectl get node gke-cluster-1-default-pool-06afea80-dsrr -o json | jq '.status.allocatable'
{
  "attachable-volumes-gce-pd": "127",
  "cpu": "7910m",
  "ephemeral-storage": "49468794726",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "27153568Ki",
  "pods": "110"
}
 $ls -l /var/lib/kubelet/plugins_registry/
total 0
root@gke-cluster-1-default-pool-06afea80-dsrr:~#

Below are last few log lines of sriov pod

I0622 11:21:51.740168  205503 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix:intel.com ResourceName:intel_sriov_netdevice DeviceType:netDevice Selectors:0xc00000cea0 SelectorObj:0xc00019afd0} {ResourcePrefix:intel.com ResourceName:intel_sriov_dpdk DeviceType:netDevice Selectors:0xc00000cec0 SelectorObj:0xc00019b130} {ResourcePrefix: ResourceName:mlnx_sriov_rdma DeviceType:netDevice Selectors:0xc00000cee0 SelectorObj:0xc00019b290}]
I0622 11:21:51.740251  205503 manager.go:193] validating resource name "intel.com/intel_sriov_netdevice"
I0622 11:21:51.740274  205503 manager.go:193] validating resource name "intel.com/intel_sriov_dpdk"
I0622 11:21:51.740303  205503 manager.go:193] validating resource name "intel.com/mlnx_sriov_rdma"
I0622 11:21:51.740311  205503 main.go:60] Discovering host devices
I0622 11:21:51.782986  205503 netDeviceProvider.go:70] netdevice AddTargetDevices(): device found: 0000:00:04.0 02              Red Hat, Inc.           Virtio network device
I0622 11:21:51.783151  205503 main.go:66] Initializing resource servers
I0622 11:21:51.783183  205503 manager.go:112] number of config: 3
I0622 11:21:51.783188  205503 manager.go:115]
I0622 11:21:51.783191  205503 manager.go:116] Creating new ResourcePool: intel_sriov_netdevice
I0622 11:21:51.783196  205503 manager.go:117] DeviceType: netDevice
**I0622 11:21:51.783210  205503 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_netdevice
I0622 11:21:51.783214  205503 manager.go:115]
I0622 11:21:51.783217  205503 manager.go:116] Creating new ResourcePool: intel_sriov_dpdk
I0622 11:21:51.783221  205503 manager.go:117] DeviceType: netDevice
I0622 11:21:51.783226  205503 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_dpdk**
I0622 11:21:51.783229  205503 manager.go:115]
I0622 11:21:51.783232  205503 manager.go:116] Creating new ResourcePool: mlnx_sriov_rdma
I0622 11:21:51.783235  205503 manager.go:117] DeviceType: netDevice
I0622 11:21:51.783240  205503 manager.go:130] no devices in device pool, skipping creating resource server for mlnx_sriov_rdma
I0622 11:21:51.783244  205503 main.go:72] Starting all servers...
I0622 11:21:51.783248  205503 main.go:77] All servers started.
I0622 11:21:51.783252  205503 main.go:78] Listening for term signals

Could someone help what could be problem. Is it problem with nodes( virtual machine) which dont have any interfaces as per the requirement specified.

Some node information
================
# lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 03)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:03.0 Non-VGA unclassified device: Red Hat, Inc. Virtio SCSI
**00:04.0 Ethernet controller: Red Hat, Inc. Virtio network device**
00:05.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG

#ethtool -i eth0
driver: virtio_net
version: 1.0.0
firmware-version:
expansion-rom-version:
bus-info: 0000:00:04.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

**Comment by zshi-redhat** [comment]
@ravikumar1907 From the log, it seems that you're trying to use sriov components to discover virtio device, which is not "supported". You may want to add a node which has SR-IOV devices.

**Comment by ravikumar1907** [comment]
> @ravikumar1907 From the log, it seems that you're trying to use sriov components to discover virtio device, which is not "supported". You may want to add a node which has SR-IOV devices.

@zshi-redhat - Do you by chance know which instance type in GKE spoorts SR-IOV.? I failed to any documentation for enahanced networking support in GCP/GKE

**Comment by zshi-redhat** [comment]
> > @ravikumar1907 From the log, it seems that you're trying to use sriov components to discover virtio device, which is not "supported". You may want to add a node which has SR-IOV devices.
> 
> @zshi-redhat - Do you by chance know which instance type in GKE spoorts SR-IOV.? I failed to any documentation for enahanced networking support in GCP/GKE

@ravikumar1907 I'm not familiar with GKE. From a quick search with google, it seems not supported: https://stackoverflow.com/questions/33114144/does-google-compute-engine-offer-sr-iov-single-root-i-o-virtualization

**Comment by ravikumar1907** [comment]
> > > @ravikumar1907 From the log, it seems that you're trying to use sriov components to discover virtio device, which is not "supported". You may want to add a node which has SR-IOV devices.
> > 
> > 
> > @zshi-redhat - Do you by chance know which instance type in GKE spoorts SR-IOV.? I failed to any documentation for enahanced networking support in GCP/GKE
> 
> @ravikumar1907 I'm not familiar with GKE. From a quick search with google, it seems not supported: https://stackoverflow.com/questions/33114144/does-google-compute-engine-offer-sr-iov-single-root-i-o-virtualization

@zshi-redhat  Yes, even  I saw this.

**Comment by martinkennelly** [comment]
I am closing this issue because SR-IOV does not seem to be supported on GKE.
