### ISSUE TITLE
Updating the google docs with current model and making it with public view

### ISSUE THREAD

**Issue by rkamudhan** [intel/sriov-network-device-plugin#25]
@ahalim-intel Is that possible to update the current doc [https://docs.google.com/document/d/1Ewe9Of84GkP0b2Q2PC0y9RVZNkN2WeVEagX9m99Nrzc/edit#](https://docs.google.com/document/d/1Ewe9Of84GkP0b2Q2PC0y9RVZNkN2WeVEagX9m99Nrzc/edit# ) with latest architecture and host link public in the README.md ?

**Comment by ahalim-intel** [comment]
Sure! We will update it soon.

**Comment by ahalim-intel** [comment]
Done
