### ISSUE TITLE
SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required 

### ISSUE THREAD

**Issue by xzjxush** [intel/sriov-network-device-plugin#258]
The version of k8s is v1.13.10.
The version of os is centos7.3.1611.
Network card used is Intel Corporation I350 Gigabit Network Connection (rev 01).
I followed "https://github.com/intel/sriov-network-device-plugin" for operation, however, I could not make it.
And it always printed "SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required ..." in the the description of testpod1.
There is no errror or warning in the log of kube-sriov-device-plugin.
How should i troubleshoot for this?

**Comment by zshi-redhat** [comment]
@xzjxush the error in sr-iov cni indicates that no VF device ID is passed from Multus. It looks to me that maybe your net-attach-def doesn't contain the sriov resource name annotation. could you paste the sriov net-attach-def? and also check if there is sufficient resource in kubelet node status.

**Comment by xzjxush** [comment]
My net-attach-def is defined as below: 

`apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{"k8s.v1.cni.cncf.io/resourceName":"intel.com/intel_sriov_netdevice"},"name":"sriov-net1","namespace":"default"},"spec":{"config":"{ \"type\": \"sriov\", \"cniVersion\": \"0.3.1\", \"name\": \"sriov-network\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"10.56.217.0/24\", \"routes\": [{ \"dst\": \"0.0.0.0/0\" }], \"gateway\": \"10.56.217.1\" } }"}}
  creationTimestamp: "2020-07-27T04:46:45Z"
  generation: 5
  name: sriov-net1
  namespace: default
  resourceVersion: "2726489"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/sriov-net1
  uid: 2c3edab8-cfc4-11ea-89fa-246e962471e4
spec:
  config: '{ "type": "sriov", "cniVersion": "0.3.1", "name": "sriov-network", "ipam":
    { "type": "host-local", "subnet": "10.56.217.0/24", "routes": [{ "dst": "0.0.0.0/0"
    }], "gateway": "10.56.217.1" } }'
~                              `
kubelet node status :
`[root@172 ~]# kubectl get node
NAME             STATUS   ROLES    AGE   VERSION
172.24.140.100   Ready    master   21d   v1.13.10
`

**Comment by amorenoz** [comment]
@xzjxush , did you add the request/limits to your pod spec?
Something like:
```
 resources:
      limits:
        intel.com/intel_sriov_netdevice: "1"
      requests:
        intel.com/intel_sriov_netdevice: "1"
```
Alternatively you could use the [sriov admission controller](https://github.com/openshift/sriov-dp-admission-controlle) to inject it dynamically

**Comment by xzjxush** [comment]
@amorenoz  
> did you add the request/limits to your pod spec?
yes。

@zshi-redhat  
thank you, I reinstalled multus plugin and my problem has been solved.

**Comment by zshi-redhat** [comment]
> @amorenoz
> 
> > did you add the request/limits to your pod spec?
> > yes。
> 
> @zshi-redhat
> thank you, I reinstalled multus plugin and my problem has been solved.

Cool, glad to hear it worked!
I'm closing this issue, feel free to re-open or file another one in case any further issues.
