### ISSUE TITLE
SRIOV-netdevice cannot be discovered by device plugin 

### ISSUE THREAD

**Issue by peng-isi** [intel/sriov-network-device-plugin#260]
## What issue would you like to bring attention to?
I tried to attach a VF of a SRIOV net device (e.g. Mellanox IB) to a pod. I configured SRIOV and 4 VFs on the IB interface of a host. I built the "nfvpe/sriov-device-plugin:latest" image  on the host (hp6 in my example). After I run sriov-device-plugin daemonset, the resource list on node hp6 is not updated. Any possible reasons for this issue?

I attached the kubectl outputs as follows: 

1. #kubectl get node hp6 -o json | jq '.status.allocatable'
{
  "cpu": "16",
  "devices.kubevirt.io/kvm": "110",
  "devices.kubevirt.io/tun": "110",
  "devices.kubevirt.io/vhost-net": "110",
  "ephemeral-storage": "530610004728",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "49382120Ki",
  "pods": "110"
}

2.#lspci -nnv|grep Mellanox
21:00.0 Network controller [0280]: Mellanox Technologies MT27500 Family [ConnectX-3] [15b3:1003]
21:00.1 Network controller [0280]: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function] [15b3:1004]
21:00.2 Network controller [0280]: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function] [15b3:1004]
21:00.3 Network controller [0280]: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function] [15b3:1004]
21:00.4 Network controller [0280]: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function] [15b3:1004]

3. configMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["i40evf", "ixgbevf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["enp0s0f0","enp2s2f1"]
                }
            },
            {
                "resourceName": "mlnx_sriov_rdma",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_ib"],
                    "isRdma": true
                }    
        }
        ]
    }

4.# ls /var/lib/kubelet/device-plugins/
DEPRECATION  kubelet_internal_checkpoint  kubelet.sock  kubevirt-kvm.sock  kubevirt-tun.sock  kubevirt-vhost-net.sock

## Do you have a proposed response or remediation for the issue?

**Comment by moshe010** [comment]
The connectx-3 POR deivce_id is 1004 and you have 1018

**Comment by zshi-redhat** [comment]
> The connectx-3 POR deivce_id is 1004 and you have 1018

@peng-isi  the `devices` in configMap should be using VF device IDs.

**Comment by peng-isi** [comment]
thanks, @moshe010 and @zshi-redhat. 
You are right, I post a wrong configMap file in the previouse post. In my experiments, I actually use the following configMap:


apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["i40evf", "ixgbevf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["enp0s0f0","enp2s2f1"]
                }                                          
            },
            {
            "resourceName": "mlnx_sriov_netdevice",
            "resourcePrefix": "mellanox.com",
            "selectors": {
                "linkTypes": ["infiniband"],
                "vendors": ["15b3"],
                "devices": ["1004"],
                "drivers": ["mlx4_core"],
                "isRdma": true
            }
          }
        ]
    }
                                           
The other outputs are correct.

**Comment by moshe010** [comment]
ConnectX3 work different that you have 1 pci address which has  2 PF netdevice compare to other cards which is 1 pci address and 1 PF netdevice. Do you see warnings or errors? Can you share the logs?

**Comment by peng-isi** [comment]
@moshe010 I finally get it works as reported in #259. right now , the VFs can be detected.
