### ISSUE TITLE
controlling numa affinity of allocated VF 

### ISSUE THREAD

**Issue by RavikumarTulugu** [intel/sriov-network-device-plugin#262]
After going through the docs and code, i am still confused on how can we control the numa node of allocated VFs. we are using cpumanager to do the core allocation, sriov network device plugin to do the VF allocation, we use PF names as selectors. Our k8s is running on bare-metal.
what we are seeing is that the plugin is allocating VFs from a different node to the core list allocated by cpu manager, 
pls advise on how can we make cpumanager and device plugin work to allocate on the same numa node. 
Thanks

**Comment by zshi-redhat** [comment]
@RavikumarTulugu  you might want to enable [topology manager](https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/) in your cluster and configure to use one of the policies: restricted or single-numa-node. Sriov device plugin (with latest version) already reports numa hints via device plugin API for the topology manager to admit the pod.

**Comment by RavikumarTulugu** [comment]
we are using topology manager with best effort option

**Comment by adrianchiris** [comment]
kubelet logs might also shed some more light on whats going on.
if you are using an up to date version of sriov network device plugin then it should provide numa information for the resources back to kubelet.

kubelet device manager is generating topology hints from these resources which are then processed by the topology manager.

Some logging within topology manager code to look for:

https://github.com/kubernetes/kubernetes/blob/ebbbc57540f8467cc5b409bddbdad7dd5d4e435e/pkg/kubelet/cm/topologymanager/topology_manager.go#L180

https://github.com/kubernetes/kubernetes/blob/ebbbc57540f8467cc5b409bddbdad7dd5d4e435e/pkg/kubelet/cm/topologymanager/topology_manager.go#L199

**Comment by RavikumarTulugu** [comment]
Thanks @zshi-redhat it worked after topology manager changed from best effort to restricted.
