### ISSUE TITLE
Getting into issues when running testpmd for dpdk

### ISSUE THREAD

**Issue by geetikakay** [intel/sriov-network-device-plugin#266]
Issue while running testpmd

$ sudo testpmd -l 0-5   -w 0000:02:01.0 --
EAL: Detected 24 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-2048kB
EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:154c net_i40e_vf
testpmd: No probed ethernet devices
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=187456, size=2176, socket=0
testpmd: preferred mempool ops selected: ring_mp_mc
Done

Getting Invalid NUMA socket, default to 0. and seeing testpmd: No probed ethernet devices

It blocks my testing

**Comment by zshi-redhat** [comment]
@geetikakay is this still an issue for you? 
In the testpmd log, it indicates that there is no available hugepages and i40evf device is not probed.

**Comment by geetikakay** [comment]
@zshi-redhat  Yeah still seeing it not sure what triggers this problem.Could be setup issues but looking for pointers to debug it.
Thanks

**Comment by amorenoz** [comment]
Hi @geetikakay.
If it's a sriov-device-plugin issue, please attach the version of Device Plugin, Multus (or other) and SR-IOV CNI you're using as well as the configMaps, network-attachment-definitions and pod definition.

Other things to check:
- Your pod has the right permissions
- Your pod has access to hugepages
- You have bound the right driver to the VF (`dpdk-devbind` -s can help you there)

**Comment by geetikakay** [comment]
@amorenoz Hello .. 
I have configured hugepages in my VM .

I have set it under:

$ cat /etc/default/grub 
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8 default_hugepagesz=1GB hugepagesz=1G hugepages=2"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true


$ dpdk-devbind -s

Network devices using kernel driver
===================================
0000:02:01.0 'Ethernet Virtual Function 700 Series 154c' if=eth0 drv=iavf unused= *Active*
0000:03:00.0 'Virtio network device 1041' if=eth1 drv=virtio-pci unused= *Active*

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

No 'Misc (rawdev)' devices detected
===================================

**Comment by amorenoz** [comment]
This issue is not related to the Device Plugin so @zshi-redhat: you can close this one.
I'll help @geetikakay offline.

**Comment by zshi-redhat** [comment]
closing per Adrian's comment above.
