### ISSUE TITLE
VFIO is unsupported 

### ISSUE THREAD

**Issue by peng-isi** [intel/sriov-network-device-plugin#268]
### What happened?
I tried to configure a VFIO for Mellanox IB interface, but got the error saying that "getting resources from file unsupported deviceType:  "vfio" ".  However, I found the VFIO resource defined in  resources/vfioResource.go. I am not sure what is the correct way to configure vfio?

I used the following configmap: 

 "resourceList": [{
                "resourcePrefix": "mellanox.com",
                "resourceName": "sriov",
                "rootDevices": ["21:00.1"],
                "sriovMode": true,
                "deviceType": "vfio"
                }
                ]

### What did you expect to happen?
VFIO is supported

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by zshi-redhat** [comment]
> ### What happened?
> 
> I tried to configure a VFIO for Mellanox IB interface, but got the error saying that "getting resources from file unsupported deviceType: "vfio" ". However, I found the VFIO resource defined in resources/vfioResource.go. I am not sure what is the correct way to configure vfio?
> 
> I used the following configmap:
> 
> "resourceList": [{
> "resourcePrefix": "mellanox.com",
> "resourceName": "sriov",
> "rootDevices": ["21:00.1"],
> "sriovMode": true,
> "deviceType": "vfio"
> }
> ]

The deviceType filed is to specify the PCI device type, not device driver type, see [here](https://github.com/intel/sriov-network-device-plugin/blob/master/pkg/types/types.go#L48). Current `deviceType` only supports network device and accelerator device.
If you'd like to specify device driver type such as vfio,  it should be included in the `drivers` field, something like below:


"resourceList": [{
"resourcePrefix": "mellanox.com",
"resourceName": "sriov",
"drivers": ["vfio"]
}
]

btw, you seems using an old version of configmap. with current master branch, it doesn't support `rootDevices` yet and `sriovMode` is deprecated.

**Comment by peng-isi** [comment]
@zshi-redhat, thanks for you help. Your suggestion works!

**Comment by zshi-redhat** [comment]
thanks @peng-isi for confirming!
closing...
