### ISSUE TITLE
/bin/sh: glide: command not found

### ISSUE THREAD

**Issue by zshi-redhat** [intel/sriov-network-device-plugin#29]
'make image' failed with a fresh clone of master branch;
error message as below:

...
setting GOPATH...
updating dependencies...
/bin/sh: glide: command not found
make: *** [glide.lock] Error 127
...

The glide has been installed globally in the system, but looks like it's not callable with GOPATH set in Makefile.

If 'make' is run before 'make image'; then no error complained.

**Comment by ahalim-intel** [comment]
We need to install glide.

**Comment by ahalim-intel** [comment]
@zshi-redhat I tried to reproduce this but everything seem to work fine. I did a fresh clone and able to build docker image without any errors.
The glide is only required when the dependencies are missing or updated (i.e vendor directory, glide.lock or glide.yaml). But those files/directory are part of the source package when we clone the repo.  So, glide should not be required to run at all. Unless those files/directory are missing.
I'm suspecting the glide.lock file was modified or changed somehow. Can you please check again?

Thanks.
