### ISSUE TITLE
In PfOnly mode, allocated devices be reported as Unhealthy state

### ISSUE THREAD

**Issue by zshi-redhat** [intel/sriov-network-device-plugin#40]
When PF device is allocated to Pod, it's no longer visible in the host default namespace which may cause failure when checking link state of that device, DP in turn reports unhealthy of that device to kubelet, this will reduce one of the allocatable devices reported by kubelet and make one remaining healthy device un-allocatable.

**Comment by ahalim-intel** [comment]
This has been fixed with #50
