### ISSUE TITLE
DPDK mode without privileges

### ISSUE THREAD

**Issue by krsna1729** [intel/sriov-network-device-plugin#5]
With the device plugin, can we run DPDK apps **without** having to specify in the pod spec -

1. mount `/sriov` and `/dev/vfio`  from the host
    - leaks details into pod yaml and devices belonging to other pods

2. `privileged: true`
    - currently this is required for cgroup device permissions (not very sure)?

Are there pod and network examples of DPDK usage?

**Comment by amshinde** [comment]
It would be useful to return the actual device node that is created as a result of binding to the the driver specifies as part of the Allocate response.

**Comment by rkamudhan** [comment]
Thanks for your inputs, I believe the team is already working on. Will update soon on this.

**Comment by krsna1729** [comment]
@rkamudhan can we keep it open to track?

**Comment by rkamudhan** [comment]
@krsna1729 I think we should have a Internal sync up between the teams to align the details between the PM to clear our objectives.
