### ISSUE TITLE
Deployment story for heterogeneous cluster

### ISSUE THREAD

**Issue by krsna1729** [intel/sriov-network-device-plugin#59]
When deploying to a cluster using daemonset we would need a configmap like shown below to populate the config required the plugin.
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/9-multi-network/sriov-conf.yaml

This however assumes a homogeneous cluster.

Is there a better deployment story for heterogeneous clusters?

Would having a default behavior of auto-generating pools by discovering what VFs are bound to supported drivers and giving `sriov-netdevice`, `sriov-vfio` and `sriov-uio` names be helpful?

**Comment by ahalim-intel** [comment]
Hi @krsna1729 
This is an area we are trying to improve on. Right we it is expected that each host will have some resource definitions given in config.json. It is up to the the cluster admin to decide how the host resources will be exposed.

> Would having a default behavior of auto-generating pools by discovering what VFs are bound to supported drivers and giving sriov-netdevice, sriov-vfio and sriov-uio names be helpful?

We thought about this idea, this could be broad generalization of VFs . What about VF's on different physical networks(different  physical port offering different connectivity), port capacity etc.?

**Comment by krsna1729** [comment]
@ahalim-intel makes sense. I guess having it part of node bootstrap to generate the conf file and mounting `hostPath` to plugin container is the sane way of handling this.

**Comment by krsna1729** [comment]
reopening to track any thoughts that would increase cluster level usability of the plugin.

**Comment by krsna1729** [comment]
Linking here -

[README](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/qat_plugin/README.md)
[configmap](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/deployments/qat_plugin/qat_plugin_default_configmap.yaml)

**Comment by ahalim-intel** [comment]
> The intel kubernetes device plugin for QAT might give you ideas: it provides configmaps and takes care of device binding based on configured device drivers.

@mythi @krsna1729 The configMap does't solve the problem described here. We still need node specific configuration. The configMap just give a centralize location the config. But there's still a challenge remain if we move the config.json into a configMap. How the configMap will be generated? Should there be a configMap per node OR one general configMap with node specific key containing the  configuration? With later option, how we store and load configMap per node? 

configMap suits well if we have a common configuration across cluster. All daemonset works with one.  I am looking at other options.

**Comment by krsna1729** [comment]
@ahalim-intel If you take a look at the link, I think he is pointing at the configuration file itself not being so node specific, which allows it to be delivered as a configmap. Have extra logic in the device plugin instead of asking for specific pci slot.

**Comment by ahalim-intel** [comment]
I understood that. I meant, configMap won't help here if we have the PF PCI address based config. I'm working on another approach of defining the resource groups.

**Comment by TothFerenc** [comment]
In our case the node specific config.json files are generated during the host deployment (by an ansible playbook). But our problem is that every config.json must contain at least one pool, otherwise the sriovdp process exists, thus its pod are restarted continuously (as it is deployed as a DaemonSet). So it would be great to handle non-SRIOV capable nodes as well.

**Comment by krsna1729** [comment]
@TothFerenc maybe your scripts can add labels on nodes that have sriov and use nodeselector for the daemonset? That way you are not using a sleep and wasting an extra pod on nodes without sriov, to work around restarts.

**Comment by zshi-redhat** [comment]
> In our case the node specific config.json files are generated during the host deployment (by an ansible playbook). But our problem is that every config.json must contain at least one pool, otherwise the sriovdp process exists, thus those pods are restarted continuously (as it is deployed as a DaemonSet). So it would be great to handle non-SRIOV capable nodes as well.

@krsna1729 is right,  @TothFerenc you may want to take a look at [Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery) where the network source can discover SR-IOV capable and configured Nodes and label them with different tags/labels.

There was a [fix](https://github.com/intel/sriov-network-device-plugin/pull/65) for the similar problem in release-v1 branch. It advertise zero resource when SR-IOV capable device is not found.

**Comment by booxter** [comment]
Perhaps in this context it's worth mentioning that in kubevirt-ansible we are using a ConfigMap with per node configuration file: https://github.com/kubevirt/kubevirt-ansible/blob/28e888aca11707b2eb3ffe1ce53681a8036eebb1/roles/network-multus/templates/sriovdp.yml#L1

**Comment by krsna1729** [comment]
I guess i could have the script here to generate the config using `jq` at a known place to be mounted into the daemonset. That way its node-specific since its binding the devices there anyway.

https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/9-multi-network/systemd/sriov.sh

**Comment by ahalim-intel** [comment]
Folks, I have a prototype working that addresses this issue as well as few other common issues we are discussing in other places. I am doing a demo on next [weekly meeting](https://docs.google.com/document/d/1sJQMHbxZdeYJPgAWK1aSt6yzZ4K_8es7woVIrwinVwI/). Please join us there and give your feedback. 

Thanks

**Comment by booxter** [comment]
Hi @ahalim-intel,

Thanks for introducing the group to the idea for node agnostic deployment this
Monday. It's clear that this mode of operation may be useful in some scenarios.

That being said, it has its drawbacks. The main one I'd like to raise now
is that the new model doesn't seem to have retained compatibility with the
previous way of configuration where the admin specified PF IDs to use on a
particular node.

While configuring PFs on each node may be cumbersome, flexibility that this
ability provides is very important in some scenarios.

For example, one may have homogenous nodes in their cluster, with two SR-IOV
cards on each of them, where each card is designated to a separate allocation
pool (let's call them A and B). The cards may be of the same vendor, driver and
type, and yet they are plugged to different uplink ports and hence should be
distinguished as such (hence the two pools). If the only way to configure DP is
by specifying vendor / type / driver policies then there is no way to
distinguish between the two.

I understand that it may be helpful in some cases to not deal with particular
nodes, in which case a global assignment policy can be useful; I would like to
see a feature that allows for the setup described above retained in the new
implementation for configuration deployment though. Perhaps we can have two
additional policy queries, 'node' and 'rootDevice' which, when used, would
behave the same way as the current configuration scheme.

While the issue described above is my main concern right now, there are other
smaller ones, like, apparently, changing the configuration format in a
non-compatible way that would require properly timed upgrade steps when rolling
in new code. (Ideally, we would support the old configuration format for a more
smooth transition.) But these are relatively minor and can be addressed either in
DP or in the deployment tool of choice (though the latter seems not very optimal).

Thoughts?

**Comment by killianmuldoon** [comment]
@ahalim-intel this should be closed right?
