### ISSUE TITLE
support dev name as unique identifier for rootDevices of netDevice type

### ISSUE THREAD

**Issue by zshi-redhat** [intel/sriov-network-device-plugin#63]
Several considerations to use dev name as unique identifier for rootDevices:

1) When looking at how device plugin might work with host devices, found that current host-device cni plugin doesn't support passing ``pci address``[[1]](https://github.com/containernetworking/plugins/issues/253) for device configuration. which means if there is a device plugin for host devices, then it shall expose device name in order to work with current host-device cni plugin.
2) Use device name may help solve the open issue #58 
3) The drawback for this change is we cannot specify device name for vfio/uio interfaces. so this should only target for devices of netDevice type. 

I'd like to kick-off a discussion on whether it's feasible to use device name as the unique identifier to specify rootDevices. It may end up with nothing should be changed at this stage, but would be happy to hear any thoughts or suggestions.

**Comment by killianmuldoon** [comment]
@zshi-redhat is this closed with the pfNames selector? Or am I misunderstanding?

**Comment by zshi-redhat** [comment]
@killianmuldoon I think we can close this as host-device CNI has been enhanced to support pci address as parameter. so there is no need to change sriov device plugin.
