### ISSUE TITLE
Add section to explain each device type in the README.md

### ISSUE THREAD

**Issue by Mmduh-483** [intel/sriov-network-device-plugin#68]
Adding section to explain the added value for each of the device types ("netdevice"|"uio"|"vfio")

**Comment by saberlilydian** [comment]
Better to add examples to show the additional steps. Like how to bind the driver.

**Comment by killianmuldoon** [comment]
Can we close this off with the current state of the docs?

**Comment by killianmuldoon** [comment]
Closed as stale. Documentation has a new VF setup guide that adds to this, but additions are welcome.
