### ISSUE TITLE
Unable to mount volumes for pod "kube-sriov-device-plugin..."

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-network-device-plugin#77]
Getting this error - the SRIOVDP plugin in error state. Does anyone know how to resolve this?
  
Warning  FailedMount  34m (x190 over 6h)  kubelet, qa3-w1  MountVolume.SetUp failed for volume "sriov-device-plugin-token-ntvpw" : secrets "sriov-device-plugin-token-ntvpw" not found
  
Warning  FailedMount  4m (x195 over 6h)   kubelet, qa3-w1  Unable to mount volumes for pod "kube-sriov-device-plugin-amd64-4hrsj_kube-system(736318e8-2104-11e9-a214-246e96878b26)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"kube-sriov-device-plugin-amd64-4hrsj". list of unmounted volumes=[sriov-device-plugin-token-ntvpw]. list of unattached volumes=[devicesock sysfs config sriov-device-plugin-token-ntvpw]

**Comment by zshi-redhat** [comment]
Could you please provide more information on detailed steps and templates to help issue triage?

**Comment by killianmuldoon** [comment]
@pkdas did you manage to solve this issue?
