### ISSUE TITLE
MAC Address reflected as 00:00:00

### ISSUE THREAD

**Issue by mp0306** [intel/sriov-network-device-plugin#94]
I'm able to successfully spin-up 2 pod with SR-IOV port, and communicate between pod is working as expected, However on host/baremetal  I did notice for allocated VF its show mac address as 00:00:00:00:00:00 along with vlanID. 

Reference logs are here below:
--- root@atlnc001:~/local/multus-cni/pod# uname -a
Linux atlnc001 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

---root@atlnc001:~/local/multus-cni# modinfo i40e
filename:       /lib/modules/4.15.0-45-generic/updates/dkms/i40e.ko
version:        2.7.26

---root@atlnc001:~/local/multus-cni# ip link show enp95s0f1
9: enp95s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfec26db1 state UP mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:c2:6d:b1 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
    vf 1 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
    vf 2 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
    vf 3 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
    **vf 4 MAC 00:00:00:00:00:00, vlan 2002, spoof checking on, link-state auto**
    vf 5 MAC 00:00:00:00:00:00, spoof checking on, link-state auto

--- root@atlnc001:~/local/multus-cni# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

--- root@atlnc001:~/local/multus-cni# kubelet --version
Kubernetes v1.13.2

--- root@atlnc001:/etc/pcidp# more config.json 
{
    "resourceList":
    [
        {
            "resourceName": "sriov_net_A",
            "rootDevices": ["5f:00.1"],
            "sriovMode": true,
            "deviceType": "netdevice"
        }
    ]
}

--- lspci

5e:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 02)
5f:00.0 Ethernet controller: Intel Corporation Device 158b (rev 02)
5f:00.1 Ethernet controller: Intel Corporation Device 158b (rev 02)
5f:0a.0 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.1 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.2 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.3 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.4 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.5 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.6 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0a.7 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.0 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.1 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.2 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.3 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.4 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.5 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.6 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0b.7 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.0 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.1 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.2 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.3 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.4 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.5 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.6 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0c.7 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.0 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.1 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.2 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.3 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.4 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.5 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.6 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)
5f:0d.7 Ethernet controller: Intel Corporation XL710/X710 Virtual Function (rev 02)

---root@atlnc001:/etc/pcidp# kubectl get pods -n kube-system -o wide |grep sriov
kube-sriov-device-plugin-amd64-57pdg       1/1     Running   10         10d    10.97.126.164   atlnc001   <none>           <none>
kube-sriov-device-plugin-amd64-7d274       1/1     Running   7          10d    10.97.235.129   atlnc002   <none>           <none>
sriovpod1                                  1/1     Running   3          30h    10.97.126.167   atlnc001   <none>           <none>
sriovpod2                                  1/1     Running   3          30h    10.97.235.128   atlnc002   <none>           <none>

--- root@atlnc001:/etc/pcidp# kubectl exec -it -n kube-system sriovpod1 -- ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if60: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether a2:8c:f7:e0:d1:3d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.97.126.167/32 scope global eth0
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
25: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    **link/ether 9a:ba:b7:7b:9c:8c brd ff:ff:ff:ff:ff:ff**
    inet 10.56.217.27/24 scope global net1
       valid_lft forever preferred_lft forever

--- root@atlnc001:/etc/pcidp# kubectl exec -it -n kube-system sriovpod2 -- ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 8a:81:9f:7e:d2:35 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.97.235.128/32 scope global eth0
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
34: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 92:8c:9f:25:96:b6 brd ff:ff:ff:ff:ff:ff
    inet 10.56.217.23/24 scope global net1
       valid_lft forever preferred_lft forever

--- root@atlnc001:/etc/pcidp# kubectl exec -it -n kube-system sriovpod1 -- ping 10.56.217.23
PING 10.56.217.23 (10.56.217.23) 56(84) bytes of data.
64 bytes from 10.56.217.23: icmp_seq=1 ttl=64 time=0.204 ms
64 bytes from 10.56.217.23: icmp_seq=2 ttl=64 time=0.097 ms

-- root@atlnc001:~/local/multus-cni/pod# more 30-sriov-vlan2002.yaml 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 30-sriov
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_net_A
spec:
  config: '{
  "type": "sriov",
  "vlan": 2002,
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "rangeStart": "10.56.217.10",
    "rangeEnd": "10.56.217.250",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'

--- root@atlnc001:~/local/multus-cni/pod# kubectl logs -n kube-system kube-sriov-device-plugin-amd64-57pdg 
I0228 20:26:58.602729      14 main.go:44] resource manager reading configs
I0228 20:26:58.603191      14 main.go:59] Initializing resource servers
number of config: 1
Resource name: &{ResourceName:sriov_net_A RootDevices:[0000:5f:00.1] DeviceType:netdevice SriovMode:true}
I0228 20:26:58.603527      14 factory.go:53] Resource pool type: netdevice
I0228 20:26:58.603540      14 server.go:155] initializing sriov_net_A device pool
I0228 20:26:58.603544      14 pool_stub.go:56] Discovering devices with config: &{ResourceName:sriov_net_A RootDevices:[0000:5f:00.1] DeviceType:netdevice SriovMode:true}
I0228 20:26:58.603574      14 pool_stub.go:65] Total number of VFs for device 0000:5f:00.1 is 64
I0228 20:26:58.603581      14 pool_stub.go:67] SRIOV capable device discovered: 0000:5f:00.1
I0228 20:26:58.603598      14 pool_stub.go:70] Number of Configured VFs for device 0000:5f:00.1 is 32
I0228 20:26:58.604815      14 pool_stub.go:96] Discovered Devices: map[0000:5f:0d.7:&Device{ID:0000:5f:0d.7,Health:Healthy,} 0000:5f:0a.5:&Device{ID:0000:5f:0a.5,Health:Healthy,} 0000:5f:0a.1:&Device{ID:0000:5f:0a.1,Health:Healthy,} 0000:5f:0c.1:&Device{ID:0000:5f:0c.1,Health:Healthy,} 0000:5f:0c.2:&Device{ID:0000:5f:0c.2,Health:Healthy,} 0000:5f:0a.2:&Device{ID:0000:5f:0a.2,Health:Healthy,} 0000:5f:0b.1:&Device{ID:0000:5f:0b.1,Health:Healthy,} 0000:5f:0b.6:&Device{ID:0000:5f:0b.6,Health:Healthy,} 0000:5f:0b.7:&Device{ID:0000:5f:0b.7,Health:Healthy,} 0000:5f:0c.6:&Device{ID:0000:5f:0c.6,Health:Healthy,} 0000:5f:0a.6:&Device{ID:0000:5f:0a.6,Health:Healthy,} 0000:5f:0b.5:&Device{ID:0000:5f:0b.5,Health:Healthy,} 0000:5f:0d.5:&Device{ID:0000:5f:0d.5,Health:Healthy,} 0000:5f:0d.6:&Device{ID:0000:5f:0d.6,Health:Healthy,} 0000:5f:0d.2:&Device{ID:0000:5f:0d.2,Health:Healthy,} 0000:5f:0c.0:&Device{ID:0000:5f:0c.0,Health:Healthy,} 0000:5f:0c.7:&Device{ID:0000:5f:0c.7,Health:Healthy,} 0000:5f:0b.4:&Device{ID:0000:5f:0b.4,Health:Healthy,} 0000:5f:0b.2:&Device{ID:0000:5f:0b.2,Health:Healthy,} 0000:5f:0b.3:&Device{ID:0000:5f:0b.3,Health:Healthy,} 0000:5f:0c.5:&Device{ID:0000:5f:0c.5,Health:Healthy,} 0000:5f:0d.4:&Device{ID:0000:5f:0d.4,Health:Healthy,} 0000:5f:0a.0:&Device{ID:0000:5f:0a.0,Health:Healthy,} 0000:5f:0c.4:&Device{ID:0000:5f:0c.4,Health:Healthy,} 0000:5f:0a.4:&Device{ID:0000:5f:0a.4,Health:Healthy,} 0000:5f:0b.0:&Device{ID:0000:5f:0b.0,Health:Healthy,} 0000:5f:0c.3:&Device{ID:0000:5f:0c.3,Health:Healthy,} 0000:5f:0d.1:&Device{ID:0000:5f:0d.1,Health:Healthy,} 0000:5f:0d.3:&Device{ID:0000:5f:0d.3,Health:Healthy,} 0000:5f:0a.3:&Device{ID:0000:5f:0a.3,Health:Healthy,} 0000:5f:0a.7:&Device{ID:0000:5f:0a.7,Health:Healthy,} 0000:5f:0d.0:&Device{ID:0000:5f:0d.0,Health:Healthy,}]
I0228 20:26:58.604880      14 main.go:65] Starting all servers...
I0228 20:26:58.604899      14 server.go:166] starting sriov_net_A device plugin endpoint at: sriov_net_A.sock
I0228 20:26:58.605858      14 server.go:190] sriov_net_A device plugin endpoint started serving
I0228 20:26:58.677407      14 server.go:80] sriov_net_A device plugin registered with Kubelet
I0228 20:26:58.677432      14 main.go:70] All servers started.
I0228 20:26:58.677435      14 main.go:71] Listening for term signals
I0228 20:26:58.694152      14 server.go:101] ListAndWatch(sriov_net_A) invoked
I0228 20:26:58.694183      14 server.go:109] ListAndWatch(sriov_net_A): send devices &ListAndWatchResponse{Devices:[&Device{ID:0000:5f:0c.3,Health:Healthy,} &Device{ID:0000:5f:0c.4,Health:Healthy,} &Device{ID:0000:5f:0a.4,Health:Healthy,} &Device{ID:0000:5f:0b.0,Health:Healthy,} &Device{ID:0000:5f:0d.0,Health:Healthy,} &Device{ID:0000:5f:0d.1,Health:Healthy,} &Device{ID:0000:5f:0d.3,Health:Healthy,} &Device{ID:0000:5f:0a.3,Health:Healthy,} &Device{ID:0000:5f:0a.7,Health:Healthy,} &Device{ID:0000:5f:0a.1,Health:Healthy,} &Device{ID:0000:5f:0d.7,Health:Healthy,} &Device{ID:0000:5f:0a.5,Health:Healthy,} &Device{ID:0000:5f:0b.6,Health:Healthy,} &Device{ID:0000:5f:0c.1,Health:Healthy,} &Device{ID:0000:5f:0c.2,Health:Healthy,} &Device{ID:0000:5f:0a.2,Health:Healthy,} &Device{ID:0000:5f:0b.1,Health:Healthy,} &Device{ID:0000:5f:0b.5,Health:Healthy,} &Device{ID:0000:5f:0b.7,Health:Healthy,} &Device{ID:0000:5f:0c.6,Health:Healthy,} &Device{ID:0000:5f:0a.6,Health:Healthy,} &Device{ID:0000:5f:0d.2,Health:Healthy,} &Device{ID:0000:5f:0d.5,Health:Healthy,} &Device{ID:0000:5f:0d.6,Health:Healthy,} &Device{ID:0000:5f:0b.4,Health:Healthy,} &Device{ID:0000:5f:0c.0,Health:Healthy,} &Device{ID:0000:5f:0c.7,Health:Healthy,} &Device{ID:0000:5f:0a.0,Health:Healthy,} &Device{ID:0000:5f:0b.2,Health:Healthy,} &Device{ID:0000:5f:0b.3,Health:Healthy,} &Device{ID:0000:5f:0c.5,Health:Healthy,} &Device{ID:0000:5f:0d.4,Health:Healthy,}],}

**Comment by cliffburdick** [comment]
@mp0306 this might be my misunderstanding of Intel cards, but I don't believe it auto-assigns MACs to the VFs. I think you need to set them yourself.

**Comment by ahalim-intel** [comment]
> @mp0306 this might be my misunderstanding of Intel cards, but I don't believe it auto-assigns MACs to the VFs. I think you need to set them yourself.

@cliffburdick  The VFs are assigned with a MAC address on Intel NICs. You can see it through sysfs but ip command doesn't show it.

See the output below for a Fortville NIC:

```
$ ip link show enp2s0f0
3: enp2s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 000000000100 state UP mode DEFAULT qlen 1000
    link/ether 3c:fd:fe:a1:3e:c0 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 00:00:00:00:00:00, spoof checking on, link-state auto, trust off
    vf 1 MAC 00:00:00:00:00:00, spoof checking on, link-state auto, trust off
    vf 2 MAC 00:00:00:00:00:00, spoof checking on, link-state auto, trust off
    vf 3 MAC 00:00:00:00:00:00, spoof checking on, link-state auto, trust off
$ cat /sys/class/net/enp2s0f0/device/virtfn0/net/enp3s2/address
8e:b0:ac:dd:e6:5b

```

**Comment by zshi-redhat** [comment]
This (all zero mac address) looks like an issue of iproute which doesn't reflect the right MAC address for VFs,  SR-IOV CNI or DP shall have nothing to do with how mac address is displayed. Regarding the vlanID for the VF, SR-IOV CNI configures Vlan on each VF according to SRIOV CNI configuration, VlanID will be set to 0 when VF is released.

I'm closing this issue for now as I didn't see anything that can be done in device plugin. Please feel free to re-open if any further suggestions. Thanks for reporting the issue!
