### ISSUE TITLE
VF are not getting updated on deletion of POD

### ISSUE THREAD

**Issue by mp0306** [intel/sriov-network-device-plugin#97]
This is Part 2 of issue reported in  https://github.com/intel/sriov-network-device-plugin/issues/94

Once POD is delete, VF is not  getting return to its free pool. IP Link output shows VF being assign to given VLAN rather then nullifying its record. In this case POD was assign to VF 4 and once its deleted ip link continue to reflect as being assign to POD.

---root@atlnc001:~/local/multus-cni# **ip link show enp95s0f1**
9: enp95s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfec26db1 state UP mode DEFAULT group default qlen 1000
link/ether 3c:fd:fe:c2:6d:b1 brd ff:ff:ff:ff:ff:ff
vf 0 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
vf 1 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
vf 2 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
vf 3 MAC 00:00:00:00:00:00, spoof checking on, link-state auto
**vf 4 MAC 00:00:00:00:00:00, vlan 2002, spoof checking on, link-state auto**
vf 5 MAC 00:00:00:00:00:00, spoof checking on, link-state auto

**Comment by zshi-redhat** [comment]
Vlan manipulation is done in SR-IOV CNI, device plugin gets nothing to do with the Vlan setting and releasing, Perhaps this issue shall go to SR-IOV CNI repo.
btw, there is a feature enhancement [PR](https://github.com/intel/sriov-cni/pull/71) of SR-IOV CNI which supports r[esetting Vlan to default value 0](https://github.com/intel/sriov-cni/pull/71/files#diff-73126a8b935928a81f24ce95cd923a2dR302), I guess that should fix the problem above.

**Comment by zshi-redhat** [comment]
> Vlan manipulation is done in SR-IOV CNI, device plugin gets nothing to do with the Vlan setting and releasing, Perhaps this issue shall go to SR-IOV CNI repo.
> btw, there is a feature enhancement [PR](https://github.com/intel/sriov-cni/pull/71) of SR-IOV CNI which supports r[esetting Vlan to default value 0](https://github.com/intel/sriov-cni/pull/71/files#diff-73126a8b935928a81f24ce95cd923a2dR302), I guess that should fix the problem above.

And also you can see from the RP that it can be extended to support setting various VF properties such as mac address, rate limit, spoof check, trusted vf etc. The config will come from net-attach-def and applied by SR-IOV CNI.

**Comment by pkdas** [comment]
If VLAN is not reset to 0, it is very likely that SRIOV CNI failed to do releaseVF successfully.
I have seen similar issues and I think reproducible if you create/delete multiple PODs with multiple VFs on the same PF at the same time. This is a SRIOV-CNI issue, please update to the latest SRIOV CNI and check if the problem occurs.

**Comment by killianmuldoon** [comment]
@mp0306 did you manage to resolved this issue?

**Comment by killianmuldoon** [comment]
Closing as stale - this is  a CNI issue so future updates/issues on this should be opened in that repo: https://github.com/intel/sriov-cni
